[package]
name = "sessionspaces"
version = "0.1.7"
edition = "2021"
license-file = "../../LICENSE"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
dotenvy = { workspace = true }
humantime = { version = "2.3.0" }
if_chain = "1.0.3"
itertools = { version = "0.14.0" }
k8s-openapi = { workspace = true }
kube = { workspace = true }
ldap3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, default-features = true }
strum = { workspace = true }
telemetry = { path = "../telemetry" }
time = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true, features = ["limit", "util"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
wiremock = "0.6.5"
