apiVersion: v2
name: events
description: Data Analysis event triggering
type: application

version: 0.2.0

dependencies:
  - name: argo-events
    alias: argoevents
    repository: https://argoproj.github.io/argo-helm
    version: 2.4.20
    condition: argo-events.enabled

  - name: metacontroller-helm
    version: 4.15.0
    repository: oci://ghcr.io/metacontroller
