argo-events:
  enabled: true
  controller:
    containerSecurityContext:
      runAsUser: 36055
      runAsGroup: 36055
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 1
        memory: 4Gi

eventBuses:
  - name: default
    namespace: events
    resources:
      requests:
        cpu: 10m
        memory: 1Gi
      limits:
        cpu: 100m
        memory: 4Gi

eventSources:
  generic:
    - beamline: i15-1
      stompConfig:
        user: guest
        password: guest
        host: i15-1-rabbitmq-daq.diamond.ac.uk
        port: 61613
        destination: /topic/public.worker.event
    - beamline: b01-1
      stompConfig:
        user: guest
        password: guest
        host: b01-1-rabbitmq-daq.diamond.ac.uk
        port: 61613
        destination: /topic/public.worker.event
  webhook:
    - name: webhook-test
      beamline: test-beamline
      port: 12000
      webhook:
        webhook-test:
          port: "12000"
          endpoint: /example
          method: POST

genericServers:
  stomp:
    enabled: true
    logLevel: INFO
