argocd:
  enabled: true
  targetRevision: HEAD
  extraValueFiles:
    - dev-values.yaml

events:
  enabled: false
  targetRevision: HEAD
  extraValueFiles:
    - dev-values.yaml

groups:
  enabled: true
targetRevision: HEAD

kyverno:
  enabled: true
  targetRevision: HEAD
  valuesObject:
    admissionController:
      replicas: 1
      container:
        resources:
          limits:
            cpu: 200m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
    backgroundController:
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi

sessionspaces:
  enabled: true
  targetRevision: HEAD
  extraValueFiles:
    - dev-values.yaml

sealedsecrets:
  enabled: false
  targetRevision: HEAD
  valuesObject:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

workflows:
  enabled: true
  targetRevision: dev-values-pt5
  extraValueFiles:
    - dev-values.yaml

graphProxy:
  enabled: true
  targetRevision: HEAD
  extraValueFiles:
    - dev-values.yaml

dashboard:
  enabled: true
  targetRevision: HEAD
  extraValueFiles:
    - dev-values.yaml
