{{- if index .Values "argo-events" "enabled" }}
  {{- range $eventSource := $.Values.eventSources }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $eventSource.name }}
  labels:
    workflows.diamond.ac.uk/beamline: {{ $eventSource.beamline }}
    workflows.diamond.ac.uk/machine-uid: "36242"
spec:
  service:
    ports:
      - port: {{$eventSource.port }}
        targetPort: {{$eventSource.port }}
  {{- if $eventSource.webhook }} 
  webhook:
    {{- $eventSource.webhook | toYaml | nindent 6 }}
  {{- end }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: waffle-generic
  labels:
    workflows.diamond.ac.uk/beamline: i15-1
    workflows.diamond.ac.uk/machine-uid: "36055"
spec:
  generic:
    waffle-example:
      insecure: true
      jsonBody: true
      url: "stomp-service.events.svc:80"
      config: |
        user: guest
        password: guest
        host: i15-1-rabbitmq-daq.diamond.ac.uk
        port: 61613
        destination: /queue/public.worker.event.workflows
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: visr-generic
  labels:
    workflows.diamond.ac.uk/beamline: b01-1
    workflows.diamond.ac.uk/machine-uid: "36055"
spec:
  generic:
    visr-example:
      insecure: true
      jsonBody: true
      url: "stomp-service.events.svc:80"
      config: |
        user: guest
        password: guest
        host: b01-1-rabbitmq-daq.diamond.ac.uk
        port: 61613
        destination: /topic/public.worker.event
{{- end }}
