{{- if .Values.metacontroller.enabled -}}
apiVersion: workflows.diamond.ac.uk/v1alpha1
kind: Trigger
metadata:
  name: example-trigger
  labels:
    workflows.diamond.ac.uk/source: webhook
    workflows.diamond.ac.uk/beamline: test-beamline
spec:
  enabled: true
  eventName: example
  workflow:
    template: example-template
    parameters:
      - name: jpg
        messagePath: body.parameters.jpg
      - name: jpeg
        messagePath: body.parameters.jpeg
      - name: tif
        messagePath: body.parameters.tif
      - name: tiff
        messagePath: body.parameters.tiff
      - name: png
        messagePath: body.parameters.png
{{- end }}
