{{- if .Values.metacontroller.enabled -}}
apiVersion: workflows.diamond.ac.uk/v1alpha1
kind: ClusterTriggerTemplate
metadata:
  name: example-trigger
  labels:
    workflows.diamond.ac.uk/source: webhook
    workflows.diamond.ac.uk/beamline: test-beamline
spec:
  enabled: true
  eventName: example
  workflow:
    template: example-template
    parameters:
      - name: tif
        path: parameters.tif
      - name: tiff
        path: parameters.tiff
      - name: png
        path: parameters.png
        default: "true"
---
apiVersion: workflows.diamond.ac.uk/v1alpha1
kind: ClusterTriggerTemplate
metadata:
  name: waffle-trigger
  labels:
    workflows.diamond.ac.uk/source: generic
    workflows.diamond.ac.uk/beamline: i15-1
spec:
  enabled: true
  eventName: waffle-example
  workflow:
    template: echo-workflow-template
    triggerOnMessageType: stop
    parameters:
      - name: message
        path: name
    
---
apiVersion: workflows.diamond.ac.uk/v1alpha1
kind: ClusterTriggerTemplate
metadata:
  name: visr-trigger
  labels:
    workflows.diamond.ac.uk/source: generic
    workflows.diamond.ac.uk/beamline: b01-1
spec:
  enabled: true
  eventName: visr-example
  workflow:
    template: echo-workflow-template
    triggerOnMessageType: start
    parameters:
      - name: message
        path: name
{{- end }}
