{{- if .Values.metacontroller.enabled -}}
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: trigger-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: argoproj.io/v1alpha1
    resource: eventsources
  childResources:
    - apiVersion: argoproj.io/v1alpha1
      resource: sensors
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      version: {{ .Values.metacontroller.hooks.sync.version }}
      webhook:
        url: http://workflows-metacontroller.events/sync
    customize:
      version: {{ .Values.metacontroller.hooks.customize.version }}
      webhook:
        url: http://workflows-metacontroller.events/customize
{{- end }}
