{{- if index .Values "argo-events" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: echo-input
  labels:
    workflows.diamond.ac.uk/science-group-examples: "true"
  annotations:
    workflows.argoproj.io/title: echo-input
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"
spec:
  entrypoint: test-permissions
  arguments:
    parameters:
      - name: input
        value: "placeholder"
  templates:
    - name: test-permissions
      container:
        image: busybox
        command: [/bin/sh, "-c"]
        workingDir: /data
        args:
          - "echo {{`{{ workflow.parameters.input }}`}}"
{{- end }}
