//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "oidc_tokens")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub issuer: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub subject: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub encrypted_refresh_token: Vec<u8>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
