localstack:
  enabled: true
  debug: true
  enableStartupScripts: true
  startupScriptContent: |
    #!/bin/bash
    awslocal s3api create-bucket --bucket k8s-workflows-test --region unsupported
  replicaCount: 1
  resource:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

oidc-mock:
  enabled: true
  replicas: 1
  template:
    podAnnotations: []
    labels: []
  image:
    image: ghcr.io/soluto/oidc-server-mock
    imagePullPolicy: Always
    port: 80

  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  env:
    - name: ASPNETCORE_ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: ASPNETCORE_ENVIRONMENT
    - name: SERVER_OPTIONS_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: SERVER_OPTIONS_INLINE
    - name: LOGIN_OPTIONS_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: LOGIN_OPTIONS_INLINE
    - name: LOGOUT_OPTIONS_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: LOGOUT_OPTIONS_INLINE
    - name: API_SCOPES_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: API_SCOPES_INLINE
    - name: API_RESOURCES_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: API_RESOURCES_INLINE
    - name: USERS_CONFIGURATION_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: USERS_CONFIGURATION_INLINE
    - name: CLIENTS_CONFIGURATION_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: CLIENTS_CONFIGURATION_INLINE
    - name: ASPNET_SERVICES_OPTIONS_INLINE
      valueFrom:
        configMapKeyRef:
          name: oidc-mock-configmap
          key: ASPNET_SERVICES_OPTIONS_INLINE

  nodeSelector: []
  affinity: []
  tolerations: []

argo-workflows:
  artifactRepository:
    archiveLogs: true
    s3:
      accessKeySecret:
        name: ""
        key: ""
      secretKeySecret:
        name: ""
        key: ""
    endpoint:
      valueFrom:
        configMapKeyRef:
          name: localstack-configmap
          key: endpoint
    bucket: k8s-workflows-test
    region: unsupported
  controller:
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 128Mi
  server:
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
        ephemeral-storage: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
        ephemeral-storage: 128Mi
  executor:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

ingresstlssecret:
  enabled: false
s3sealedsecret:
  enabled: false
bitnamisecret:
  enabled: false

postgresql-ha:
  postgresql:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  pgpool:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  persistence:
    storageClass: netapp
    size: 5Gi

oauth2-proxy:
  enabled: false
  # replicaCount: 1
  # ingress:
  #   enabled: false
  # redis:
  #   master:
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 256Mi
  #       limits:
  #         cpu: 200m
  #         memory: 512Mi
  #   replica:
  #     replicaCount: 0
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 200m
  #     memory: 512Mi
