apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: analysis-platform
  title: Analysis Platform
  description: >
    The data analysis workflows platform deployment. The deployment consists of a Kubernetes virtual cluster (vcluster),
    in which Argo Workflows is deployed alongside accompanying services and a monitoring stack. Policies are created with
    Kyverno and continuous delivery is achieved with ArgoCD.
   - argocd
  tags:
    - kubernetes
    - argo-workflows
    - argo-cd
    - kyverno
    - vcluster
    - monitoring
spec:
  owner: group:data-analysis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argo-workflows-openapi
  title: Argo Workflows OpenAPI
  description: Simple service to expose the Argo Workflows Schema
  tags:
    - rust
  annotations:
    github.com/project-slug: DiamondLightSource/workflows/backend/argo-workflows-openapi
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/workflows/docs/
spec:
  type: service
  lifecycle: production
  owner: group:data-analysis
  system: analysis-platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sessionspaces
  title: Sessionspaces
  description: Simple service to create and configure namespaces for every instrument session
  tags:
    - rust
  annotations:
    github.com/project-slug: DiamondLightSource/workflows/backend/sessionspaces
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/workflows/docs/
spec:
  type: service
  lifecycle: production
  owner: group:data-analysis
  system: analysis-platform
dependsOn:
  - ispyb-api
  # graph-federation - after it is added
  ---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: graph-proxy
  title: Graph Proxy
  description: Simple service which acts as a proxy between Argo Workflows Server and the Diamond Graph
  tags:
    - rust
  annotations:
    github.com/project-slug: DiamondLightSource/workflows/backend/graph-proxy
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/workflows/docs/
spec:
  type: service
  lifecycle: production
  owner: group:data-analysis
  system: analysis-platform
dependsOn:
  - ispyb-api
  - argo-workflows-openapi
  # graph-federation - after it is added
  ---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-daemon
  title: Auth Daemon
  description: Daemon service for accessing the supergraph from within a workflow
  tags:
    - rust
  annotations:
    github.com/project-slug: DiamondLightSource/workflows/backend/auth-daemon
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/workflows/docs/
spec:
  type: service
  lifecycle: development
  owner: group:data-analysis
  system: analysis-platform
dependsOn:
  - ispyb-api
  - graph-proxy
  # graph-federation - after it is added
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workflows-cli
  title: Workflows CLI
  description: CLI tool to lint, submit workflow templates as well as create repositories that will provide template boilerplate
  tags:
    - rust
  annotations:
    github.com/project-slug: DiamondLightSource/workflows/workflows-cli
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/workflows/docs/
spec:
  type: service
  lifecycle: production
  owner: group:data-analysis
  system: analysis-platform
dependsOn:
  - argo-workflows-openapi
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workflows-frontend
  title: Workflows Frontend
  description: Frontend dashboard for workflows platform using material ui (mui) components
  tags:
    - typescript
    - mui
    - react
    - yarn
    - vite
  annotations:
    github.com/project-slug: DiamondLightSource/workflows/frontend
    diamond.ac.uk/viewdocs-url: https://diamondlightsource.github.io/workflows/docs/
spec:
  type: service
  lifecycle: production
  owner: group:data-analysis
  system: analysis-platform
dependsOn:
  - argo-workflows-openapi
  - sci-react-ui
  - ispyb-api
  - graph-proxy
  # graph-federation when it is added

