apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: argocd-oauth
  namespace: argocd
spec:
  encryptedData:
    client-id: AgBTFDvsM8zCk4VVFqGE1AgJnAmzQD7C+H5JClztocG6wZxFSgozxrquaT5khcEGfGTg8UkMu2+zXX311awYZMU5Nh1FmkeEIv/OgWyG2O0E4l+lk66p2GCD109i6/WBurJb/Qp6d+IGLQ/9+4L5R44x+c7NrrPBAWDhCbmiJMOfecvwI59y2LyvYPlnu8OND6dugBjZt2/p4H2gmQ750M/S9Sh3h4pDcTV/Tg3OShaieC9BwWk8ARpefuGNOLw2C4kbLXzBXEb3PAM4MrdsM/ooKyWqhSttZphp9G/H60CaltJ0EuySAIrtxyxoOj8qalEvHua9G3zKuUB17ffeGEQ8SWeeJbvQU6Axno1LTZHUXzj3/zH+ChVvMk+zQDpAZJE8VLavVd+skJUaXLgQ2obYYNvCrtwUlbprlPcN9JakKa8VN3ThXwhj2hcaEtWXctJx0EigHvigHAzov5zESMpyBZpH4xbJ57dso7n7lsId+jhTW0x+2matcGvuzG1vLYuijJwAknpFqdq94q77UclOu8BtZxM36GfuwT0hwsWMv+WF962VCuBC8jZ2y2KUyjbcnigkReCRoI4graXDxskup3woGDBF8SL9hKyeDgsHsI7L+TKMpvwwiF1iqFrZsPjz4C+/I7tzaB3SA9QIcgP00f+5SkTNk8R5LW5fm+5dtEEX8391Lm5J/IoSyATgXPcwwBjpcazyCkd+GnD5DZMX
    client-secret: AgBvjZ7NgOZKoDU8GpVex4rNExl5SHmWsIHQ3sRfDoYuBUHYiWholN2MdKAucigm1joVNzRiTkUNpYwNk1Wa3IIoTcXvTmxbmHDVsggVLv9IV25v7PP7YPpehrRQtoXxzhALVP+C97U1ELvf7FWChS6dTSEBP5rG5WzlIEfZaQsfAlGPDOlCM8Y9ZTy/IJsb4n0imK1b+7cVX9GnpzEZgKbcnjtJzUElR+Y79ZaKyeHtTnY+VMr5ZxMjFiK1onYVKmWk7V9WaBwqdLitfJfzlGXtPTFJax984YwwpfgjRlwwtMLvItE1gtrs9ItUPa3O5ypUbxO4h8uBizU4TaoY0UqmR7g5Szwz4w6QDFtKV/89gnQ+jg+7xu2KK6Uw6n9rfsmzkmPAtKhMFWXll/h279rQZnjy/uBk6Xq8SNxIiliwwB+b3HSvRcDB5A1fouQBAOVm+gmUUsUPdp1SIMXRpdvLiQj48AmzSmsISzPnZgGJ6hS0pTgOM5DbPtKG/tGi89BB5BHOzqD1hiGZwIVFMKl3UOQZmzqAlXG/n9EA7gGAMzeg8cPTjoaT82jKXpU7PZU8spdPxK8ysoE14h1HrqsCV/qamoucwllS+iqkW2T+vBjomYQ2TG/IAjK6SLL+5arOHuhbHEwGVB1qefVyWF+Kh7xIyUyD3xK26pf0aLfm+ixyguM64TtThAnUK66cDCaluzRnBUXeZGCCerXRSCdszrCt0t9Vk554T42CmxhLSQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: argocd-oauth
      namespace: argocd
