FROM docker.io/library/rust:1.97.1-bookworm AS build

WORKDIR /app

RUN cargo install cargo-auditable

COPY argo-workflows-openapi/Cargo.toml argo-workflows-openapi/Cargo.toml
COPY graph-proxy/Cargo.toml graph-proxy/
COPY sessionspaces/Cargo.toml sessionspaces/
COPY sessionspaces-controller/Cargo.toml sessionspaces-controller/
COPY auth-gateway/Cargo.toml auth-gateway/
COPY auth-core/Cargo.toml auth-core/
COPY auth-core/migration/Cargo.toml auth-core/migration/
COPY auth-broker/Cargo.toml auth-broker/
COPY telemetry/build.rs telemetry/build.rs
COPY telemetry/Cargo.toml telemetry/Cargo.toml
COPY Cargo.toml Cargo.lock ./

RUN mkdir -p argo-workflows-openapi/src \
  && touch argo-workflows-openapi/src/lib.rs \
  && mkdir -p graph-proxy/src \
  && echo "fn main() {}" > graph-proxy/src/main.rs \
  && mkdir -p sessionspaces/src \
  && echo "fn main() {}" > sessionspaces/src/main.rs \
  && mkdir -p sessionspaces-controller/src/bin \
  && touch sessionspaces-controller/src/lib.rs \
  && echo "fn main() {}" > sessionspaces-controller/src/bin/webhook.rs \
  && echo "fn main() {}" > sessionspaces-controller/src/bin/api.rs \
  && mkdir -p auth-gateway/src \
  && echo "fn main() {}" > auth-gateway/src/main.rs \
  && mkdir -p auth-broker/src \
  && echo "fn main() {}" > auth-broker/src/main.rs \
  && mkdir -p auth-core/src \
  && touch auth-core/src/lib.rs \
  && echo "fn main() {}" > auth-core/src/main.rs \
  && mkdir -p auth-core/migration/src \
  && touch auth-core/migration/src/lib.rs \
  && mkdir -p telemetry/src \
  && echo "fn prebuild() {}" > telemetry/src/lib.rs

RUN touch --date @0 sessionspaces-controller/src/lib.rs sessionspaces-controller/src/bin/api.rs \
  && cargo build --release --package sessionspaces-controller --no-default-features --features api --bin api

COPY . .

RUN touch sessionspaces-controller/src/lib.rs sessionspaces-controller/src/bin/api.rs \
  && cargo auditable build --release --package sessionspaces-controller --no-default-features --features api --bin api

FROM gcr.io/distroless/cc-debian12@sha256:d703b626ba455c4e6c6fbe5f36e6f427c85d51445598d564652a2f334179f96e AS deploy

COPY --from=build /app/target/release/api /api

ENTRYPOINT ["/api"]
