FROM docker.io/library/rust:1.97.1-bookworm AS build

WORKDIR /app

RUN cargo install cargo-auditable
COPY auth-core/Cargo.toml auth-core/
COPY auth-core/migration/Cargo.toml auth-core/migration/
COPY Cargo.toml Cargo.lock ./

COPY . .

RUN touch --date @0 auth-gateway/src/main.rs \
  && cargo build --release --package auth-gateway

RUN touch auth-gateway/src/main.rs \
  && cargo auditable build --release --package auth-gateway

FROM gcr.io/distroless/cc-debian12@sha256:e5d81ddde149641e2a9ba55be4545bc125c67de07508b03ba4c22e6eb0ded5aa AS deploy

COPY --from=build /app/target/release/auth-gateway /auth-gateway

ENTRYPOINT ["/auth-gateway"]
