[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-fmt",
    name = "cargo fmt",
    language = "system",
    entry = "cargo fmt --check",
    types = ["rust"],
    pass_filenames = false,
  },
]
