{{- if $.Values.artifactSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.artifactSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  access-key: {{ $.Values.artifactSecret.accessKey }}
  secret-key: {{ $.Values.artifactSecret.secretKey }}
{{- end }}
