# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: userinfo-roles-clusterroles
spec:
  concurrent: false
  steps:
  - name: valid-posix
    try:

      - create:
          resource:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: workflow-creator
              namespace: ($namespace)
            rules:
              - apiGroups: ["argoproj.io"]
                resources: ["workflows"]
                verbs: ["create"]
      
      - create:
          resource:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: create-workflows
              namespace: ($namespace)
            subjects:
              - kind: User
                name: test-user
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: Role
              name: workflow-creator
      - command:
          args:
          - create
          - --filename=workflow.yaml
          - --as=test-user
          - --as-user-extra=workflows.diamond.ac.uk/posixuid=12345
          entrypoint: kubectl
      - command:
          entrypoint: kubectl
          args:
            - get
            - workflows
            - -A
            - -oyaml

      - assert:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: valid-posixuid
              labels:
                workflows.diamond.ac.uk/creator-posix-uid: "12345"
            spec: {}