# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: userinfo-roles-clusterroles
spec:
  concurrent: false
  steps:
  - name: valid-posix
    try:
      - command:
          args:
            - create
            - clusterrolebinding
            - impersonator
            - --clusterrole=allow-impersonation
            - --user=$(kubectl config view --minify -o jsonpath='{.users[0].name}') 
          entrypoint: kubectl
      - command:
          args:
          - create
          - --filename=workflow.yaml
          - --as=$(kubectl config view --minify -o jsonpath='{.users[0].name}')
          - --as-group=$(kubectl config view --minify -o jsonpath='{.users[0].name}') 
          - --as-user-extra=workflows.diamond.ac.uk/posixuid=12345
          entrypoint: kubectl
      - assert:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: valid-posixuid
              labels:
                workflows.diamond.ac.uk/creator-posix-uid: "12345"
            spec: {}