apiVersion: v2
name: k6-op
description: k6 chart for k8s

version: 0.1.1

appVersion: "1.16.0"
dependencies:
  - name: k6-operator
    repository: https://grafana.github.io/helm-charts
    version: 4.3.0
