# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-ping-graph
  namespace: {{ .Release.Namespace}}
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-configmap
      file: ping-graph.ts
  runner:
    env:
      - name: KEYCLOAK_CLIENT_ID
        valueFrom: 
          secretKeyRef: 
            name: graph-proxy-k6-auth
            key: KEYCLOAK_CLIENT_ID
      - name: KEYCLOAK_CLIENT_SECRET
        valueFrom: 
          secretKeyRef: 
            name: graph-proxy-k6-auth
            key: KEYCLOAK_CLIENT_SECRET
      - name: KEYCLOAK_TOKEN_URL
        value: https://identity-test.diamond.ac.uk/realms/dls/protocol/openid-connect/token
      - name: GRAPH_URL
        value: http://graph-proxy.graph-proxy.svc.cluster.local:80/graphql
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
  starter:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi

