apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
  namespace: ks10000-1
  ownerReferences:
  - apiVersion: v1
    kind: ServiceAccount
    name: argo-workflow
    uid: ks12345
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: ks10000-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: visit-member
  namespace: ks10000-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: visit-member
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:https://identity-dev.diamond.ac.uk/realms/dls/k6Operator
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:13827
