{
 "title": "ArgoCD",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "cluster",
    "query": "label_values(argocd_cluster_info, server)"
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Sync Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(argocd_app_sync_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (health_status)",
       "legendFormat": "{{health_status}}"
      }
     ]
    },
    {
     "title": "Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (sync_status)",
       "legendFormat": "{{sync_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval]))) by ($grouping)",
       "legendFormat": "{{$grouping}}"
      }
     ]
    },
    {
     "title": "Sync Failures",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(round(increase(argocd_app_sync_total{namespace=~\"$namespace\",phase=~\"Error|Failed\",dest_server=~\"$cluster\"}[$interval]))) by ($grouping, phase)",
       "legendFormat": "{{phase}}: {{$grouping}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_count{namespace=~\"$namespace\",dest_server=~\"$cluster\"}[$interval])) by ($grouping)",
       "legendFormat": "{{$grouping}}"
      }
     ]
    },
    {
     "title": "Reconciliation Performance",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~\"$namespace\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "K8s API Activity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_k8s_request_total{namespace=~\"$namespace\",server=~\"$cluster\"}[$interval])) by (verb, resource_kind)",
       "legendFormat": "{{verb}} {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(workqueue_depth{namespace=~\"$namespace\",name=~\"app_.*\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pending kubectl run",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(argocd_kubectl_exec_pending{namespace=~\"$namespace\"}) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{app_kubernetes_io_component=\"application-controller\"}",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{app_kubernetes_io_component=\"application-controller\"}[1m])",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{app_kubernetes_io_component=\"application-controller\"}",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "AppSet Controller Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{app_kubernetes_io_component=\"applicationset-controller\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{app_kubernetes_io_component=\"applicationset-controller\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_component=\"applicationset-controller\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Objects Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1137 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resource_objects{namespace=~\"$namespace\",server=~\"$cluster\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "API Resources Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1365 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(argocd_cluster_api_resources{namespace=~\"$namespace\",server=~\"$cluster\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Cluster Events Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1371 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(argocd_cluster_events_total{namespace=~\"$namespace\",server=~\"$cluster\"}[$interval])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  { "title": "Repo Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Git Requests (ls-remote)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Git Fetch Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"fetch\", namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Git Ls-Remote Performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{request_type=\"ls-remote\", namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{app_kubernetes_io_component=\"repo-server\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{app_kubernetes_io_component=\"repo-server\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app_kubernetes_io_component=\"repo-server\", quantile=~\"1.0|1\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Redis Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Requests by result",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_redis_request_total{namespace=~\"$namespace\"}[$interval])) by (failed)"
    }
   ]
  }
 ]
}