{
 "title": "GraphProxy",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "RateInterval", "label": "Rate Interval", "query": "1m,5m,10m,30m,1h,6h" }
  ]
 },
 "panels": [
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors in Querys and Mutations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(graph_proxy_errors_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request duration in milliseconds (p50)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(graph_proxy_request_duration_ms_milliseconds_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration in milliseconds (p95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(graph_proxy_request_duration_ms_milliseconds_bucket[$__range]))\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration in milliseconds (p99)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(graph_proxy_request_duration_ms_milliseconds_bucket[$__range]))\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second (All Pods)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(graph_proxy_requests_total{k8s_pod_name=~\"graph-proxy.*\"}[$RateInterval]))",
     "legendFormat": "Sum of Graph Proxy Pods"
    }
   ]
  },
  {
   "title": "Requests Per Second (All Pods)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(graph_proxy_requests_total{k8s_pod_name=~\"graph-proxy.*\", request_type=\"mutation\"}[$RateInterval]))",
     "legendFormat": "Mutations"
    },
    {
     "expr": "sum(rate(graph_proxy_requests_total{k8s_pod_name=~\"graph-proxy.*\", request_type=\"query\"}[$RateInterval]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(rate(graph_proxy_requests_total{k8s_pod_name=~\"graph-proxy.*\", request_type=\"subscription\"}[$RateInterval]))",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  {
   "title": "Requests Per Second Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(graph_proxy_requests_total{k8s_pod_name=~\"graph-proxy.*\"}[$RateInterval])",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Query Depth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Query depth (p50)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(graph_proxy_query_depth_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query depth (p95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(graph_proxy_query_depth_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query depth (p99)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(graph_proxy_query_depth_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean depth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graph_proxy_query_depth_sum[$__range]))\n/\nsum(rate(graph_proxy_query_depth_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query Complexity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Query complexity (p50)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(graph_proxy_query_complexity_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query complexity (p95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(graph_proxy_query_complexity_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query complexity (p99)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (rate(graph_proxy_query_complexity_bucket[$__range]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean complexity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graph_proxy_query_complexity_sum[$__range]))\n/\nsum(rate(graph_proxy_query_complexity_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}