export const fakeTasks = [
  {
    id: "1",
    workflow_id: "1",
    name: "task-1",
    status: "completed",
  },
  {
    id: "2",
    depends: "1",
    workflow_id: "1",
    name: "task-2 DKJFOKJLSKDMFO",
    status: "completed",
  },
  {
    id: "3",
    depends: "1",
    workflow_id: "1",
    name: "task-3",
    status: "running",
  },
  {
    id: "4",
    workflow_id: "1",
    name: "task-4 ERFBAK3KJ34",
    status: "running",
  },
  {
    id: "5",
    workflow_id: "1",
    name: "task-5 EOI909D",
    status: "completed",
  },
  {
    id: "6",
    depends: "3",
    workflow_id: "1",
    name: "task-6 KNMNE9",
    status: "running",
  },
  {
    id: "7",
    depends: "3",
    workflow_id: "1",
    name: "task-7 KLDJF034 DFJSOID 039402KDJO",
    status: "running",
  },
  {
    id: "8",
    depends: "3",
    workflow_id: "1",
    name: "task-8",
    status: "pending",
  },
  {
    id: "9",
    depends: "6",
    workflow_id: "1",
    name: "task-9",
    status: "pending",
  },
  {
    id: "10",
    depends: "9",
    workflow_id: "1",
    name: "task-10",
    status: "pending",
  },
  {
    id: "11",
    depends: "10",
    workflow_id: "1",
    name: "task-11",
    status: "pending",
  },
  {
    id: "12",
    depends: "5",
    workflow_id: "1",
    name: "task-12",
    status: "completed",
  },
];
