webhook:
  image:
    registry: ghcr.io
    repository: diamondlightsource/workflows-sessionspaces-webhook
    tag: staging
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  deployment:
    replicas: 1

api:
  image:
    registry: ghcr.io
    repository: diamondlightsource/workflows-sessionspaces-api
    tag: staging
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 400m
        memory: 512Mi
  opa:
    url: https://authorisation-test.diamond.ac.uk
