grafana:
  rbac:
    create: false
    pspEnabled: false
    pspUseAppArmor: false

  serviceAccount:
    create: false
    name: default-full-access-mounted

  ingress:
    enabled: true
    path: "/"
    hosts:
      - grafana.workflows.diamond.ac.uk
    tls:
    - hosts:
      - grafana.workflows.diamond.ac.uk
      secretName: letsencrypt-grafana-workflows-diamond-ac-uk

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://thanos-workflows-query-frontend:9090
        isDefault: true

thanos:
  existingServiceAccount: "default-full-access-mounted"
  existingObjstoreSecret: prometheus-sthree-secrets

  query:
    enabled: true
    ingress:
      enabled: true
      pathType: Prefix
      hostname: thanos-query.workflows.diamond.ac.uk
      extraTls:
        - hosts:
          - thanos-query.workflows.diamond.ac.uk
          secretName: letsencrypt-thanos-query-workflows-diamond-ac-uk
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 2Gi

  queryFrontend:
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 2Gi

  storegateway:
    enabled: true
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 2Gi

  receive:
    enabled: true
    tsdbRetention: 1d
    persistence:
      enabled: false
    service:
      type: LoadBalancer
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 2Gi

  compactor:
    enabled: true
    retentionResolutionRaw: 30d
    retentionResolution5m: 30d
    retentionResolution1h: 1y
    consistencyDelay: 30m
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 2Gi
