grafana:
  rbac:
    create: false
    pspEnabled: false
    pspUseAppArmor: false

  serviceAccount:
    create: false
    name: default-full-access-mounted

  ingress:
    enabled: true
    path: "/"
    hosts:
      - grafana.workflows.diamond.ac.uk
    tls:
    - hosts:
      - grafana.workflows.diamond.ac.uk
      secretName: letsencrypt-grafana-workflows-diamond-ac-uk

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://thanos-workflows-query-frontend:9090
        isDefault: true
