apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: pod-securitycontext
spec:
  namespaceTemplate:
    metadata:
      labels:
        app.kubernetes.io/managed-by: sessionspaces
  steps:
    - try:
        - create:
            file: resources_base.yaml
        - sleep:
            duration: 10s
        - create:
            file: resources_pod.yaml
        - assert:
            file: assert_pod.yaml
        - sleep:
            duration: 10s
        - assert:
            file: assert_pod_mutation.yaml
