{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oauth
  namespace: workflows
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgBoEh41o1tKPnN0+gW959cAqPWUgaaFL6ZpCH4B9lhTyqRtKeQuN31cnJ2wRWSi6pzurdzcB0ZA3eLvQwFfCH6FW6ynSJGG0l22VvLFPI/cEavmcq7ri7vlYcHPeguZH5ac1QEc2kYa4XmhLlZsv7r9OXMjLD2W9Vo9E6W83Pr1wmnd4Bl5cT7KJRAlyZrMMT9YoQOiloPdh/XhrFvopaLwWCZCsSwIIEHPZmxxYz1Rzz3F4f6DXwRcCM2BUGmlh6JkqcwF+FivSQ+6Naswz7FriXRLpNnzXzRQHRWdJHB5oz6DdYE7CWaUzVAWK4vVxGXA+hmXJVxDAwx/HKRdVd3d+G4WWu9vgtVQM34TplDW1YlkXvH+2mXntNJjf9hGqfsmjMDYaAOjYiOuex+EruVzomoaBSHOJ/H84ZBYMkgRqqqXZt/IS1U0ctj/OyWLtAGm4WTXKs/S8m2t8eCmc4hqRxTamPksDroif1CztMsj8aMP/x3/QOCHPohu07+yuw00oCP0ju2iomDB0vfCwt+yU5WAVabRbo4RmFjPvyiz09Nb0aB+QiB3tW+k2wkU3plRxwlqs5aV7lK9fX7ENkmk1a7xzryBLu3U6bXYEmG5A3PLYieEWTfEN8N8wQyQFKO5PBFxLAY9Llh4l7YGWWJEVmsiHs3JR0FcafuuVUenjWMPHaGeveVGRvkuL6tksR5KAWrn8xSh2VFbJ3mn8T5KyyD2AuLgMlEhq1mYFk/01g==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oauth
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oauth
  namespace: workflows
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgBwwEV/dQqSSe3wwfptwpQgrfzZc40+689MbMkaE6fC4szL1ZMhqJbZUvs6BOLEE3eirHyHwyBnUpn20Sw0VY56K5z2fLOjQ3Js1kgN+QDeg7gH0hIAGQybrWFCgGFgnbdovDwBLgt8saTxQsSK2WGtwSl/MWZB+SvOrpbtRd0kQhv8sXDnbJf28PlZAtIQik/u1rUC/vI1C58fzNxxjBPrX9cc7RiOSV2HjoPIcwZyQs0HGerZy4LfNw5MiN25pwozsHFd/slDo/Pi+7bzPgVledPlMVyBgpidJrVh0cEf68CAp2q+J3Irkz04zYe0X7zcoll6L88W239OLUIoBnyRzop51NOur57LUdUK4DsUPovgOZPQTgKIJnmAHLG+Ms359RZWrmOYjuZuiYpLgU6Z0NmK/BDwzVcktYVOglbPJNiRL+PYzDQf8PEhQYbDPtjyDaZW3I34ElzSNIoBdOITXHY1PNYV2CQZux/YGY25pBjdK9tfUOBTgqtpXICGVPLEuws/yNd97iUQj5ApwkYuG934OechyG9MF0Lc6zeJCCGpnFz400f5WaFL9bB1fe5bncdb90GpQ0/9INQ3fNvJQJFWqQfMfHU2pFpQkvO1VmoZGEdZa9w/WlMxDk2yW5fsH0TFJjxmNwUyVzTd2yLKqUTdtBiS7RxBKMlQmCsoW5rXpDgzKmnZ5Vj0bcbn9txwTQQ2fAqPmlBG+yGcLDWK2ewv6QcS9ayetk9QuzxPVg==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oauth
      namespace: workflows
    type: Opaque
{{ else }}
{{- end }}

