{{- if eq .Values.cluster "argus" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-keys
  namespace: workflows
spec:
  encryptedData:
    encryption_private_key: AgCnShCyevKH8BNTdoWe6/hhtaeopQekLyF4MYmfX7WdwGGXcQcm+XY4ImslQqZsjNdoLc8pt+nrPHJq3q8OOKjptJTLnh89wyrfzY6ngHGOc0tMN197TL6JNLocFxEIeNZZWtWV0bNECaHEg4T+3YhUbfxn5MCmC3A60Y7TAccvLIBN1HsbVc3rNEmaEFrzqHpoYTonR3NFn/V/8BpW6Aa63CoWLPqRJbPtjA2AL85YOM6Fpwzs7CY6Lqla7Q+mhkwpABivD/wn4cp2uUeydSWs0nw6xYFWumvy28YQ35MeWGK2jH7S1qG3aJVQbM8yvetmGUJkCIbL+HQeoYqyQRzuvxySDXBiHsYOZB+/GtN1BOOZSWsb7Lj1OvOMvzVAM/MwRab1qi1s9eB17pFX6/szGvrh9W0hdBdSj642jWUP5WwNug3R/+qEBm7IjcJTZfDjI1zWs4yYj6VYdliIBVOgMkmbgY970SpIN9zzSwiyAab3zY2e0ZYxGUMhGagunpT9ZGgvdIYG9T/x39WjStSFYRyO2CTJMiymWJXKZ9iSE5Gu1QAvmXBP/x/jHalTGWhpdVco4pQHOSQvOeCPwfyGgD5lJ7HuT/mMG7NnL+AJQ58dbD6iWsUCy74TVabJei9lejnPtc1rQ0U+bbnc2xon/ssot/asbgepDO0rdRBsWUh+rT9q0lvOglzFvLb/rk/ZmKDTB5LOYPGtvTqBnbRYZFCWO32hi5/KKzv06TmHoWNQmFIgJBCBdXlOrQ==
    encryption_public_key: AgAqbZBnhxP7lqlHacFFxslMEBd5VXqDWKbuGs8NaxEsU8ak7E0h07DoEXZAoxxAeKtZClBtPrdv0pYC9QZZ12Qzl4YV4iJU3Q+ciX55DH69ZIFG8at8kJb28M4I7OOCwQNggaTHMd6Mh9YoKMfMk4oYOQruv9Xf2mzM1MMLE9elAU+goz986+8+JUOyF8iu6Yf+JYy84+vDga1jiwD09bB2YTF7npR0XmEYS8i3W0U7mzZkKFxgcQdfpSJubevkjeD/PnGgdb88FeaAgdbV8pxg+fQqpEchtH8ix2boQ5ydVDsfl9kQDQeNf/2Wv55Fi/sc3j3vHPZR2WHxgoAZysKJiMC2oTAqdyTstF9jF5CmjOJtSLANI2spWNXqhTZJT5tr/U1Roky2ziIUChyGyTUirBuIO+GYLSaJlOfPrWX1EsAkmWxnCA0Q2XigpttJkCg1tgA4nuTY5WlJLhWD3m2/T+FkGnhDf0WF77CAwXf0eGuilXKY7JDBChljAqfuALRim5TrPuAN5Y8rKZnqji0rOILJYZKm50qcvDckiZ1lHu21L2tj4BYir/OWiA9x9wfW+YGUjKiy1/7gVW1dmdMwyU1+TfTgGqh+BS5JDca3To4UPPFxyD6o+pQU5Tn2HLns5oe47P6nAzECgV8KmqHnEc375f9QoWlgab4c8WbARYyk62/ZdqESKZvu+MZYGEZHo85ijUpdA0zOnjRknsxOi15/+nuJciK0XRZGwRtXdgzZmHB+M1IaEhsCjA==
  template:
    metadata:
      name: auth-keys
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-keys
  namespace: workflows
spec:
  encryptedData:
    encryption_private_key: AgBLJDrOtH4DhgDEfSTIZiNRQA19npMaw2JKEwUKUbLRkKueweT854spXiPNKS9QGl2yS6MJ0hkc4btV0tXvnHJqvmGhLJT+Xx10gvGGAUgxuUUYQDGwbILZgjITcR17Z7I73bMpkabYmmF6H/dvWHFpQ1yKtGMzMYM0GLkEL5UUbW4ekbViyUDF4lPWsk/deFOfB6B+d2gDd7HYGa3NXO/olqNPXtgEQT6lGawtMF2TJC1ly9azOGXP4unopjrmfLtj0gzxn1Z2nUI71kZ9FOLMHf5Ncf8VOybnucIWcRD5QITuyEohVsIgjur8xK9e9YS0sKon2lziO/tSbcGJSLHkDmyfP100Vv50Z02q9CEjg/TAJ1RU/BgVXcukNZZmlWYnCwvp40ZyIDtTr/FBPq/HlFhV6mpCUxDl2HqfA8eLW4bPbzULmCeuqoQMf99waA5ezUoFNClpHPxrO0kg3j64GU3SY+DCsOynfdvKsCBOLascyCMbDAfPLXVAllzF9T/djBkY+RfE1lZnYaDbc6R5bN/UVKOFHRte5VHWyLanRXpdJA5Kz2PWa9XMywXVG6RV2J1QbwAswD1kbxQ+vvkFPtZx10EmPsOYdMo/BNVaSn7dX/PI+F4kiIpBkJ0EsLpUC29K2QChg7Bj52OjZVNWkhrw8skXYAQGZrQSgMzrgdDsF9CG+Sjmp66zRwpy03q/dXEf3dO/YqLnOu/S8EyasI4AZ6jAFGoPiTW2lxpjqGoM55aVSE8kaD058Q==
    encryption_public_key: AgBXNRkPk5MXfOKd7sabwIltG4dEAgJXpd3GBh1Nd/24P9/lF+W6cXQfiNuzr1SJcGRKuDdebZAi9Z0IvdNS0uSaDqZRvhiD5EvJdFo2BSuqq8Akdx20Chun8qAGyalkpqXi9UInwRkcwxP8Rk37JI80xNCr+LEV2sIxz54FjzGpcMEjiFGI8dSRrqdW8XmQ/WLk08qzGroJn+nw8lLGL75Pl7OOMucwXuQXaDDbngkZ+i21RRS+7rRay8b6h78nBY0aieGIsShiy23jjjT85xMiRaDshW09Xci+5BN6Y0NX73fBjNLJhi7tWrUtQbmqqRbiFoIh1CTlTyiuhwlWpUeHv48Aw02W6K061LKYzvgTOAB88QdcnlXFj0+bkqi+/E/obLVl7/Pis2eLzQwVFYt8EpRcK40dOl1CrlJ603AjxRFb/nBtPEcfBvqh+aauEyJ+QkMd6kn5M36cy16Ku5TFCmXIudXfrD3LoojIEHHBT/Med6tWoid4jR5tAdO6ZeREesKwjf5s7skN9Ba/zYN/WdPTJBAAZjsQ1d2kOQYV4HxM7ZoOv3Q6RQd/9pXFzpGJxx0ioPSb6m6eo7iESZjhaw7/wxM1wKbDPDfbIlKc8WLAH8knHaeHZwDBlZNl5PiYfer7oEAMHplPinJmniPM5fCY1k+aAgv4++I9b/27WqRo6vevcP2i51xc+/0cemhBLoy8F71ip8RQ+5mrsgzj0xW04mklehqrxfwJX//V59MKzka2v/N03fCQzA==
  template:
    metadata:
      name: auth-keys
      namespace: workflows
    type: Opaque
{{- end }}
