{{- if eq .Values.cluster "argus" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-keys
  namespace: workflows
spec:
  encryptedData:
    encryption_private_key: AgB6lbfP2GRA0+f7GlqWkh2WrmwRnxuw2h9jBMFT1MbyiPo+oHMnQAJ/0jfNDBsVg217HUzGR1qFy7s41J7mKOxhqRubS+eghd39RDLQMvjbZXSpRfouRhqE/FOZHxNxcJ2S1qYSBBOO4J/6YQKm1EEAadua9qdoDSZNpz2+XMYtLkD/Uv5cK+nUGVeeND+knDhycxx6Xtoow1xetvTZKzNInXGv3a/GhdT08s3IP1QerPn7I7jyO/MA2CnG76v3wzdg0gVTfjfiocBS713qPfCTs9M2ZstKf9nitBR5e0N2Mx8CZKX+k4MTFCPMMPt+wFgVNQTGluz1MbnT3UHnA+XK6VeAUfbP2pRnkDHB3nJNsddx0XD785inGMr8YL8+hXsAqd5c0E0XhblfOgQAy/5bAScKqrB8yJsurqboQMN2UIgpGmQ4Ft54jJkWqx0RFx4A8phcRROfapkcAWG6+K00aUXF6rFNfpfDHzh4V9tt31iQQZindWG5qd4ZbMvXTjOTF7Wc3tYZLoBAp3c5tEKths6qAHj4o/CaDg8leBgVOP+mYSH2RRIChbTB6yfjRzj1IYs+NaTnbKytYFFiXxIDCruLAslkohLoWpbq84Iq4S4pBaDef7yMHBDN5txBA9YenMcznvyDDkls6xsBz7N247MDx/6EayNtdzPmhnRsBHivL/hA3edwyGN0OzoY7KQmTbgq++9pvKjuKA4ZBnjS0huEIY8c8VzmM7hbqr5VUMUOJ3JVY5F1/zc+RQ==
    encryption_public_key: AgBEgti1BCG01+NIdrEw0Cs8ro2QKtIawS0SgjupGdLnYetRYZwG+LCmBwctKAFm5VKfEDfDPCaTxqmp79y3X2K/Q8i4neOe5cDgrtHdMkI1G/vHuxIhtJjm767XSdamqrHsk4pkzLDABW7hHB+8gMF5SDW3SwRjA9mt8Mr2q2DDh1aqngHozJ4brwz8SQAnfPT1SXclzDuwPzm1EBa7IvjlnfnCqocaIAvjeRF76WDUtSySAHnOwxTRZFSdUDpl0NDGoJ4r09TsuMzAFc6m5xsXIK1E8tvp6YfjrWo0ztGQXA5qMh/C0NHi7L9C+XVW2+yNxoyKH86W23pByTq4I8xOffStYkom8w39My+WEJVk1AtrPXxtMboonz6K3RlOZY6qN4575JPYoDCzxhialWML5Dq9AX/qcyIAl3mac+lS89Yf67dCfswSJQ12QnzWB/U4aALw8FYkkSE0GNy+Z/txI3a2YMK1lD6u8uu0sUBScXf+pFIHlotdXapXaGqVoWTc/shYI+WOyDl5XggNFl0xn1z8xtIULedTehJ1wQGuX+Wp1Unf6HQ3PGvyigMNzlSIknE7eso+aVcHFOoJ/BH5i3elB1V3xdhrMO8N0RQFkfAgLog2woZjoJiEjy7AUbgMlUN7CYfBDK6hpOXeevUdkILv6gSCqj0U5/HxnXCK3S8J0Id1dEWbluIDVt0/k27pTuFBU4d1Z4jbLyI0TuqWrJnGHBwuOYiPVf0pFPdBvFhYtR/cz1J7Nj7grA==
  template:
    metadata:
      name: auth-keys
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-keys
  namespace: workflows
spec:
  encryptedData:
    encryption_private_key: AgBmZoYH6XJArtXrQUTTNtkWjA5aRE8N0KXNtJOPv7iJMqVVnopIt9V3eaTwaPraM///0qf6QfrjDpYgz9FhodtY2/mkTspciI0a8FMTInzC4E6X3wPawhlenGUI3VWOUfoOySQAk7uVpClo5Mz9+RpJt2h0JiBXxEFrxirFiEoG0OoPC+iJbM9ablRRQUwJJhjMobfUPne5yja/RIx70g/r63YlxaIOXWilZ0b3Tp5z/7cD5rYSQdS2inguY5TbFJb4om62CUh4TWIHldzKAKLwE8vaq4cE0e3MHkU9Ysmt5wASvcDXkVJbx90dipkIM6wNUPei8VR9bQTS1JZ7ZIi/byT8/jznVDSBKKfE5QlrYz1pPGxtdPZGbwfsY3CzxjVRa8pnlKoeabJwmcpebQ1vvOzCX+mI+tghRGuDk5RYO3TFBLz940Yhtgt/lfnhN2icYXdpkqS/7vD01A3J0r9rNZ8u12GSr9WTplZNktBsdnoUcMxZCCQB9ysPthY2fRtfnU21GN9GliikTbwdL7ZDqgJTPQuaU0CbCia9CvYmrY02aQkWZ/KW3Bk8zWl1eafW8geGy812qmVaqaTIOyzRoAtbO9/LYF7R1JmTixJyi2i6El1pATRSvTYhBidiTzcokMpCAtRCZl0zfLX7/IjHPJUJ2SPZnepu0H5CZQL+vTxn75Gx3/U7XxfzwiNebjPEZunS3JqFrOOSPnlP/L+CLGJB57DDjS+ecAf4Of4Y5QFZfCLlX172m72JTw==
    encryption_public_key: AgBjO5rEwIA5rHOvmUylmTL+XSFVQI/AtXHdg6Yorv/rg3hYDezBE4eDp1eKvPZy60NU5UDkgoOzNKwD3wbMjlR3SM/7tHS8m8iCd/Xuv8Jgs1LBIUBBYDdAaIs7ieqp71G3i75wX06yci7Fg99Ufn5HlRathzdndS2KoddJdEr+b1hj4ESE4HDpsAhDFg20KAqFw+8hbDqVT2dBwF0+677HBDJ3cvF5XJszx/jyX9AZx36Yuh0Xbu9VJzp6Sz1qit26MCby9uak62DFNJRmawL6BKqxdx7c1TXtJoFfEenmROYMiiEER1z+Wtr+nM4oMNkvTEOFZCqNHUFIgXjbVZ9t8mNhFzjSyf2rU3luW9a6+pkSpaAd9YTtoANhVsypZlhg9KTqhSkh2zdKHt6ihZ/oqTsMhwhDfF9cXcdo+PyPfAoOKsn7pOv6BtafVVBHaAn3/A/D9q4EhhSPBsbegXsk2YdBPXbRR5lN2OtYyw15Je3tOu6dVSAPIros/ItpVlfFdU+AnAKIiCALai96lo760ewIY5ja2OJV8P9MTtKl+NvdMmBe4TmpVucQzOBoNjmRrmdNViyao0dLhbl7WL3Tp3qMEWiXcev0L46Nr1L9UCSAdHUxo1kCVvsfHw3sd8od+M3TnTsxYTgp2o9fPDhd06CDECTHH40UtsVWQJyDmeGconOIMGWh2CcwDpbMJ6mq5De93qlHD250YUa25b/2hLy9M3drk+/NjCaOarJqA9q9lIO7gMAO4F0Nkg==
  template:
    metadata:
      name: auth-keys
      namespace: workflows
    type: Opaque
{{- end }}
