{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-gateway-config
  namespace: workflows
spec:
  encryptedData:
    config.yaml: AgAVUclxqYra6pqcnx7piqB0OkxuIcsEWrGO0chMJYvWVwBt1t5HWNwEhUuFECXA3LY3EizJlALH/5/ejt9N7y4Ybu+mkAyM+dPFSPvO2qBP70rWfkTtN4UsT4gXemRhXIr8jA0EO8EjfkhziX/Sqktf6q/6ssguHdtOxQHNKeORN9cbqSnk+R7uCcOM/EFpYsG2sncJf5yyh8dainuQ3/TBPxaRPcMvX5io9zZtRpEG/LisQGnyXAMgLtp/Treik7V9Io7Dq4xI7yn4rswX+Hg13nnj3YWoqYXDrzp/PVNtngepjjHdbxt045bJ7NvF1UN/aM7fFLrZG2v17aKphH1118XTzxMWFByGYSXWEBXQG3wwkNMDPwIUY3EM+npacwEO+5JiTcsnO926V0lJyaQJfD0Ar8MQBgV0cQEoHB0nAUsbUbO6dHwKzOs53lLCssv1wPxmzSf59K0ThqdpJYfFowNrNxQxUeFL49gTyiifEuCzZ1+5t4wF/+NInKRWB92Bq2cbgYb6FE14ZHBeA+lz4JTvUWg1gGhhBDYVh9xyHQct4RiaaSzquWgNLqHYPLDGQktUan1+L57jjATNnp5kvI6M2jrIDCyE4gWDy3OAoOXKnMoFsQHJat2hVLP7O3EvifxczJs2npfG23abX9itxN+XkJYGMScgQlNCavmUN67dX0j0jkXUzQVBOF8VdWkAlMc+GPqu+Ve7b4xyJgGLGLV7CW6xpZBJA2plQmpvTL3fbRm55x8KZGxaQj+nauRlisXVSmGqyaTdakyLYdaMNDlZ7BoTqJLxA750GESXz8fr1kIfbJxYDo3tjKNtM7r3XUJ2Yu258Pw1OW6ZZmS8sJb1zi1JSPI7qGihYlwPBWkpKlzR9AO+iyl3uKI3xZjtMtNzlxdhAqzc4cn04OMwrYHaPPZmU3rQMKL6LFDd3ckJQj5zl12B8pIdFHcLrO57ikv4wRdPtr9KuebA7Zo9mjCeMVmqw3haiS3P7CTMtUcRUrJW84jsgB+34d6kLzC7ZTO19Hze7oKkzH7ltAkT+UbXGxRP/KIKwLRix8xSYkMuaRsCMTpUl2p4jmoMQu+iPgTyr+iQ9nJ1GuJMd1VP8WfazD/KLi/RBHu5QIH+Ixy3QVgxd5K48roLDeng0IG9dAZFCjKkYv50yuk6cuyaALklQVUZSucqzfc2Uics6XCI3tP6S++GI3JCggEBTP9dG5RGd1ukjJGvtALwKK9dGGZIVMPKrF2F3PtBImNwAlrYMketfhPkdnTwaZ69xFHS9YuYd8ACWjytMgKEoml0HnBetbrAE/l0+qhAmULPEWGqbn0qDVXpMOo2Bp2ivlw=
  template:
    metadata:
      name: auth-gateway-config
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-gateway-config
  namespace: workflows
spec:
  encryptedData:
    config.yaml: AgAWvjSHHBxYpvAgt4MhlS8hxOZzIbm8FV55p1+nHN1ywJXvrCHM8ZHZMzFI3bbDLldM9mo8YaTEjan6nwzCKNsJD4oeG56p+xpWn956+Si4A28qJbk0dFaL534hO4YemlW0lZ/W9lyk9JheqEtIEp3mP9DJy2UFm2tb4vXcHgTwVRzeYEZP5LNzqfzZZ3vno+Vg/BTO6iuoYVNLdMC3UYGdsWUUhXJgYOCktNKFNFy6q6PTyuJtaief5PsCNtfeV/nIiFZ/KfbY4asvhhDqrJxG8oUxTtH4zMG7AAfJe9WdsofHu1FNZMjHSiqe57nDTHVHejKkojYSXJ+z0DdpgP/k8/sRHWvbWew4TYk3HxALlNdoVDH/LKr70gwz4QXXLqYjiwq1l7q5Ui2sAsqTOHt0ux6zpqoAb41yZDZh+30YR1uwkPc7pcbYxnR8CRlg33dtebrki0tjTcIUcCf9VKsnN8tkNNdU5lvAxRD8e6PFuTwrFKkdZsVUJ6/q85VIv2Yvz8Ujzt1tQI6o8mzInBUCaMeElCBeqpXW9EqWFRhtCA+JXPpnPFJz5grd7wYFyxmlXFDD7t1OXGv5o3Q9UdRKwCAEvfLT7Q26iGMsH9tLhKZNnHPzafabtGG6zR1wHtKfS0naZ5xy/3QHMIJIG52Mt2qPLwnbOwjguP3oQOuf3VpQk9+7GwNw9xsicpXDoWxYDYBfHeh2pSJSmRlYr/UgueVryvkjZDjsMKI8m5tmygPX4M8jynHoIXM6lz1tzaMpcPZwMGFUKZCj5J60zZlWOZQ336Rd3s8+IYhwWPzOP864qqZrF4s8dyDoj3mgzWujveZlLsISo6lAfN1zn1l7n5GS17oWFrliJ25elcDO4RGa0f+ArXFFVtYL7yljME+Rs0bYSrImKYMA+qSDYnRollfVP7qqdzHq5vrcdU2t+063fK8PoEn4cUaCZL8CLgcPw0uKBpa14+pUhxA3vltxCFl3OKbFUbNo5JtYjuHbRFI5AyAluTFhf+YXito3nXXNpGa91gJxAKHQSUt8cP8vfwMfzl62QZM1UWU8wOIXzDxgWXZd8ZK1HrnGcyzlp+WjaLGKIzMWct5YHQ/12OmkG7hcQ8hyc3/5vZp5IyX7uBMV+yivgnvTjKX8H+nf0P3ntr0sy0RTjzanw5s1klqG41XTh5OQSQHebHOFr5xrP5MJVfcD5yTE450dP9DugxrKLgNtF8avB1trl7Dc7ugSrY78i0zr96q02/HmNobWO/UTNvAnxoFzwBr6wIVgz8NLu+LWfm87Vwfl4SSatYdp0vwhN5EfuESwGJ0MwjRC8eIywxVi6ItOP8CSW3eQP9DvS8Pwvg==
  template:
    metadata:
      name: auth-gateway-config
      namespace: workflows
{{- else }}
{{- end }}
