{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-gateway-config
  namespace: workflows
spec:
  encryptedData:
    config.yaml: AgBBz0N6UzZb3ZjHKQ5R9Nc6SLaPpIklJrTKg8yHAbxUFmUf9IIXqgaRz7Q2dtOZ+kg/jAqGDDHZFTWSs0cCyjiAYYQlTnuYwkToNNAX17lXlp0T4b6KKo06lKbmbn332jR+rmaCIbt42fVF6PFzutatttoIosblfbotMbd8Faa5xQBHNve4TXnxhXlubdqhP4g5laLV2rqhDiF6OpOyLWyQK/uvNAlq2iNoyXy4tOiqsFgy0fBxVpnU/L2+qaD+V7VEhTz2O/WmOIWAbvZbZFI5sKWUi43oobaS2nw1j8VrjUj3RCHlZJF4TbzckhWDf6He/IdxUAr9oLkMNcSZnaAMn92qIGNffSjqsQZoKWCWmeJlY2u/fWeL8zftPl/jv9hsXm1NN5XQF5MsraVCHXPPSMUPZf6vTqu+UNhr0+17+PqoZIjRBTtmv9iCKT9wFxjK9OiRAJ2F3Be2Eam53FiBKB7JAN6msuDn/oNVtL647EtitqF8az3rhZPzqPZIZlonI8tHNyGBfPSMigxnZS5rOSnDrMJGxLt2BbmZjaIfxcRIq/CvBHcDPPch6p5C+VHpHe/rCp/OenxsRCr5D9T9OcXoRi3XCqNqqXRqIdjSwCmY96+GdI1OuRIscQXYornkbLjgMIri0AAxs28lHAKXU0ez6GZEx73o5ax5nUCnM51hGVZgrcCXgiVKpqJ0ezLCEuSX65O4yryXlXSJ60ml+tcSZ12wohV7QOJoV4kHIYkbZtbdUl422tqezdILpok29IJo41SZhlUx7E4xM3SZTYNb7ZsEXLXwnJZ1qw3lQk9H/w3UR64p1UjmOKGpdqXsonjAExRNBdADnqEqZN+RhKTnlUuSJcBDqDgEF7xVrr95FqAKCUb52c8/2EpPLeR+S+mNKfVF0BhKrx5dkfxN/tE5dYUzLPzsmtTO0hb/awAcDXPxbqIgOWA54UAhcv9AyFhB6ciStncSOHBm7Y8lSQgyo8PPUbnTDJH5T5pcIV+39EZIcPkubx6Q8MzaBFzhARyESGFzLXYScvJyR+12xv5v9/xgTP5HukyfU2yl6wpnDcgvukX/Ph2ooiqrshhcLFPtpai8Za9Iv80zAc81mtIiB+grXV+4ZOI2RP497hBXVNNp2p+UV3F4/SjcuCsbRCYJ+XFYmKIX2nTRl9MU7g4v7TYQ41ypq7wcKx3spZtTclCiAxprM9Zgh7SlMuR4KbgabKjr6r5riMmS/a1fi+Q0ks50SxfGtitvxGDLIO7K0MrAo0N0KR8xlX/mrMq8oU5IoI8yzaIC2P0b+3Yfm6dV1cGc/UA/GzLO+fdNuefubCpNHqzpXAQcVPaLxwdqCQ==
  template:
    metadata:
      name: auth-gateway-config
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-gateway-config
  namespace: workflows
spec:
  encryptedData:
    config.yaml: AgAWvjSHHBxYpvAgt4MhlS8hxOZzIbm8FV55p1+nHN1ywJXvrCHM8ZHZMzFI3bbDLldM9mo8YaTEjan6nwzCKNsJD4oeG56p+xpWn956+Si4A28qJbk0dFaL534hO4YemlW0lZ/W9lyk9JheqEtIEp3mP9DJy2UFm2tb4vXcHgTwVRzeYEZP5LNzqfzZZ3vno+Vg/BTO6iuoYVNLdMC3UYGdsWUUhXJgYOCktNKFNFy6q6PTyuJtaief5PsCNtfeV/nIiFZ/KfbY4asvhhDqrJxG8oUxTtH4zMG7AAfJe9WdsofHu1FNZMjHSiqe57nDTHVHejKkojYSXJ+z0DdpgP/k8/sRHWvbWew4TYk3HxALlNdoVDH/LKr70gwz4QXXLqYjiwq1l7q5Ui2sAsqTOHt0ux6zpqoAb41yZDZh+30YR1uwkPc7pcbYxnR8CRlg33dtebrki0tjTcIUcCf9VKsnN8tkNNdU5lvAxRD8e6PFuTwrFKkdZsVUJ6/q85VIv2Yvz8Ujzt1tQI6o8mzInBUCaMeElCBeqpXW9EqWFRhtCA+JXPpnPFJz5grd7wYFyxmlXFDD7t1OXGv5o3Q9UdRKwCAEvfLT7Q26iGMsH9tLhKZNnHPzafabtGG6zR1wHtKfS0naZ5xy/3QHMIJIG52Mt2qPLwnbOwjguP3oQOuf3VpQk9+7GwNw9xsicpXDoWxYDYBfHeh2pSJSmRlYr/UgueVryvkjZDjsMKI8m5tmygPX4M8jynHoIXM6lz1tzaMpcPZwMGFUKZCj5J60zZlWOZQ336Rd3s8+IYhwWPzOP864qqZrF4s8dyDoj3mgzWujveZlLsISo6lAfN1zn1l7n5GS17oWFrliJ25elcDO4RGa0f+ArXFFVtYL7yljME+Rs0bYSrImKYMA+qSDYnRollfVP7qqdzHq5vrcdU2t+063fK8PoEn4cUaCZL8CLgcPw0uKBpa14+pUhxA3vltxCFl3OKbFUbNo5JtYjuHbRFI5AyAluTFhf+YXito3nXXNpGa91gJxAKHQSUt8cP8vfwMfzl62QZM1UWU8wOIXzDxgWXZd8ZK1HrnGcyzlp+WjaLGKIzMWct5YHQ/12OmkG7hcQ8hyc3/5vZp5IyX7uBMV+yivgnvTjKX8H+nf0P3ntr0sy0RTjzanw5s1klqG41XTh5OQSQHebHOFr5xrP5MJVfcD5yTE450dP9DugxrKLgNtF8avB1trl7Dc7ugSrY78i0zr96q02/HmNobWO/UTNvAnxoFzwBr6wIVgz8NLu+LWfm87Vwfl4SSatYdp0vwhN5EfuESwGJ0MwjRC8eIywxVi6ItOP8CSW3eQP9DvS8Pwvg==
  template:
    metadata:
      name: auth-gateway-config
      namespace: workflows
{{- else }}
{{- end }}
