{{- if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-proxy-k6-auth  
  namespace: workflows
spec:
  encryptedData:
    KEYCLOAK_CLIENT_ID: AgAhvd6OCqb04DDzzvTwaoJbCpGBIuq47wUM6fbvRP9yMBQscZIBUMPyTVTi9qno5CKocyrXYqLMP2/vS97oY0IsWLyFV3OShMTVjMg2Q61SOW9u3JRkHkIvDLT2nCQ521T8F4IyPi6zSe0qr32cPHG8XlsA+ZzRorLP5jfs5nlbT/ajvuC9zPE+X6FD5hFpYSTn/jexn5jntFQzVz2L5oNY4jMjBF4AnKUg+0QNSVkQFfYNFA93sD5eujI7nE+9dpeWKCQFYfYM2fw3cnBWoLU/YlzSdr7XWIjZqmRQ4rTNks5tbqyaRZVP2xyBtoUqGvLwPjf5zMw5rdwQVBIzN6W1tELnZk6G1v7Y1L8vrmHiTqmtweitAM7zbVo5jLwu4hTcLyPhTX5Vyx+Y4J5RwNtWE12NOnSvu5u1jlYVk3k+idD4P7wQGRVvzwIIPs7O8G/6xICjO14RmD9FKXyook7JoDarEAhDkqTitLkxsItd2XR798Zsx+m1j7YvRo4VzKTI1dorWGq6rg+hsGHwK6RytBLLr+sesXBv8GKVb9P/zwra2w+RnCmFxzVnCayUsMrQBbZT6U0z97QqHK+wV9opHArG52C33SPQCGP2DdHQH6rTBpwXKhFTiyLEt51TCwdnHJDU1avKPHI0ps2qL9LrgBABBCaCDiIjOY46igtWS7uV3J2n1o2kC9b5wN9+vqn+wqzJhPBn43MW
    KEYCLOAK_CLIENT_SECRET: AgBXSIx82oRTptzNwlpyDPbA3sQAqC13zUMGEPBuqIYbTVLobR2fhq07UoPd/2cqO7tB/IGghaQXn29upu6nWUKuy/meeTkgYQWrZWT+1RrV3On7fszQ7Ov+Bfs3cex/jXvBT5i8MsWm9eqM335eFO6jKvH15XHYaXFxCPqsOpVYQzrCog6mRIIDTO3De0wkz1RLQN91+AM7rXqWz5XqCcCon9uzLiLbJxV8sxw36DPBOLTY/Jsc789wj9CTN1+RG9FQbGxzD0BXv+1e521uSKbWGGj4YxDqs22Z5Pe3JZLBkYoLa2MEthjHuBDv6KxHAf7zNEvZ6k9X6/eCDIddvFGnKcx8tTYbYF6ZZV1EqGt6UPSQwj6vcLxUJTM0zgL+FwYjUVxRHBPJKeELBf3To1B9lEb0iPwgXmz21dYQV+TgfRbqwkvaeNfx/tRYi0G/9jLJubDV5qyZypdsvrNKzuahBhMRQtEnR/DMQAtQl0Sg5BAx3SrQkYI9D32Xw49mUqqpqvXekrypz5C2SRM+6vhTKrEbkq9T0P0cXz0qF7B34ci3Omb5DbkbHisqd+cz891AaKB09CacpyXVocstOvv2RouLRKj6W/ya3W2X65FRFcllbFGVeZmC2RkwVKGwFN6XjkZDhCPL5khjaqp7jrsqEk0GN6JpcK9UZbGK/KyfqvLJ5h5E/y6F3t5rgdDWWW4mZxbiKZylycOQyHJHBXMXUh8DdImO/8gZUO2kI5YV1w==
  template:
    metadata:
      name: graph-proxy-k6-auth
      namespace: workflows
    type: Opaque
{{- end }}
