{{- if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-proxy-k6-auth  
  namespace: workflows
spec:
  encryptedData:
    KEYCLOAK_CLIENT_ID: AgBfgu/0rkkZ9sut6uYcVqFVRaBbUI7MQuTV15EzOjTKSdt22SBF2gUr9GQC+oHX5tnsqqpk3EE0kuq4FgN+Hb/bw2gUftzl/B7sZU/fcUOqcL4bHgtNdJ527B6JMFTL12CAJSSnwflteLYuNvKD4T514/c2tMdh1d+XYHuVs1nl/YxtdBVjrT3qX+G6kqaGCeaR/IYEIa7jE9y/1TH92rSt8pJq7l5k2vuKfw4U2+YHUO1+1pwdE9eFa5PQVgXIiynfcifEQn/QrsJdfKAbpq+IC+ZSoplcehBS52QQJ46MhvM5Dg5oGXX4U33UdrZHfnTeHte2odwANogg8d39Tmg9h6e78wbMTqKHSCcbKVq3OUr/yKpRk7D0hkJTfITr/PXAH1W+PuxHjd4mmFX3x1M8MizDVYsPZxlCIp0sv4Y+NJPtr0rYp5HzfnWVFy5Hef26plNUzE3NhtUAfDDXfb34u0em6Y60HEsG31M9AmPHyomQnaxM5uoNwHyGo4EuUh7n1+mDpkFUAYfqy8QLFoJ3pQymdoQqVToUc28DFNqpo40lsrrRoOUmfC2puQPn97njkw0CNGV5/TWl8kJ1GStkL3ayuFrz6xRLWgq+Ut/u1ItFVlNUwz7O8RiypA4glzqbWYJ5brsqu4x0hkc+3YDZ0CNCBdwu26kOhdqYJS6A1xTWXtk6lNunYcsajHmfIVPsxYnInQjBvZax
    KEYCLOAK_CLIENT_SECRET: AgBgO0BNUsJNARu6vnnzV6fhjNhpD6vbmdBZk3xyAzll49EEwrOaJi+UQLv+K4/2bUBD+R8QXh626bQwYwcljFi36mmuDDCcj7pXv9KiQp9XXXhGAo7HuzabcAQ5wplD5YrJtkL2lb+p/Z9dAPJeDO1a2fK0Yea8dC+UDwM4GIpUPhkxdas8W3nc6TfuovdXUb/CCNOVG3xwlmM3kPD2JCgynv05fZ2WU1Mfq5i48I1kAb6bY1OtFh639L7TmwPCARb6ENa7uVkwAevSP2wxfn1eqvhKcEJ7lQMEh3x8QvGad6fKKXux77kRcCA7MzEZa/XSSzshHA6LAYjmtABtR7bHkQ+XATA22qAUGy8EFhNLSN7gw8LSyYlOVIU9B0iaMBzmRfFanJCYy6nQmDqG3TPqIqNTYj4GjxyXTY7iud6g+QqqMMxDAMuOhi7gAkmoi5BsZpdFPYgA1DF7nxyhHeE/byQcE1h77LrxZQYtr7hnPBemt3dbfdgWnVy3PLsGXLyaKYWWtyeDab5X/hOYEYa+qEpAcQvJoQR81X1qgJJYJ7febSyFM+L+GmNJ84QB4lnXw4Tc5GZMfvpNVhvG/Zc5w/9Q4jjBL5CFBR0ktgMN8uif1ElYtHXiK2CESgtc86vfk2MUABfnoyHmUb0RNOgX+Ni/qvBbo0pJq+//RR9XPPzAKVUe3Fs196hFKwhnHsU5i9o9yC/Nh9RL6GARXWicWVmoqrNhW3UHliifKyRVFA== 
  template:
    metadata:
      name: graph-proxy-k6-auth
      namespace: workflows
    type: Opaque
{{- end }}
