{{- if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-proxy-k6-auth  
  namespace: workflows
spec:
  encryptedData:
    GRAPH_PROXY_BEARER_TOKEN: AgAXZd2G1Kj2F5hq0nI+WEs15sSOlYrnKLFovAyOz4ZJEms6gl+G4h4IGXwgdWw0u3gW9BeTmpYqLBJNWnPsJUUTj+w1e8yRQ4bh0yZ8IuZSVtFQ/ylYL3yJruEpxGK4KdbHTfQk2mBTQO4SZpn+F7tod028qjwrdSg+OnjzfQ7ttLHzdb5FefBEf5xb4tA1f2rP8ApKxbJIa/UeQCtRRhIqKJEBCMPpujKoma2m79kWAZDFQ3Le9+7HE0xc9ypZc32dWw+wWrj4eowvRZpfUeg/Kd3ovn0+IyEfMD+Lx73Vb04o0iWBH5/xvubdB5494qRE0295pizQEFBEiXu8VV4Er+TsuKOrqzzpfZEaxFhsVZaRw/CxbwCJbhcKeZIhOnNwhnZnWvb7bYud+qK+1zwgvs6vQu2vYdSIchQZ4N8gYvUgq0FM+ZVnR6lQDq44ww338k0rj1KTYaiyzQvR4NAXtMfAbjmOp1NpJUxzGrNXwGMNg4OvPgEWGQ3jJPtdcarGuFkW1ZieRih8qAd+G6PGd0+srrrP8pRQYOyQ1hWdLuKO+DnII5Geg85ArbJvXJSxKylApOPgtIoBWoNMR2FhQf97RDA3iRbk6nDyK0PR+eLPyunBb9LJZWsFS07t0RyATjeYubPFYazZAY/50VmorG+7DnHbzJXgF1Rkq+1HzSfuF+9OUgutSLagqbWfL9oTfoX2oSt+oDtf0mHGovUeG8ip+2DEN+M=
  template:
    metadata:
      name: graph-proxy-k6-auth
      namespace: workflows
    type: Opaque
{{- end }}
