{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-proxy-k6-auth
  namespace: workflows
spec:
  encryptedData:
    secret: 
  template:
    metadata:
      name: graph-proxy-k6-auth
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: graph-proxy-k6-auth
  namespace: workflows
spec:
  encryptedData:
    secret: AgA4DzSdtT8w1X2r/rSXgEumpa/zObyE3L6PYPxOsPkMnPVflZ+PM1xIQvGDgh2c5G5qRvGvRyh7Tz6xPAZRZX/QcrQgDz19aiKVhqbdH6CSJiXWTv6LnqMLQujVwCLYHqUfUAXfCPFl+buwHt6INlvXznTevFPS8V66z34xsenxGU+MxuazpE7Vm6iDUVhrxBtrJX7/WRdHc3YZM0sCA7SXttrahNkLSrJnpci5scsqp7nUk5e10/eEMN19iLslCAk1R+jBJwM+DGi2SEOxRS85tPdKpOBkORbx9RSEoikWSgkFOx/JjV8x0CEgGqZtU0R14/87UMYHWaeEe9ZVFLxOie6eJHnhEasSqmmgzVAj6wtVfTbVR4o6xoM9bkehxFVXANcYXg+HnWUMG5tUHH3bdAL6COxle/XUOoroBQElUvxl4XM7fAE5uDIzCgeySL3xdyOeNiwT6HS0SMdBmMlwlsnJGJU4bCZIdp2J7hfasae+cldNAC3kd7bT0NFF0bQfCbrmjUQCtKPT+DNdrVePaUF0rVtxg5Auu3v4BcOTpJRfagPiL4V94IxCyNVuvEPVRoU1XC4iWY7yi+QJ902Q0WI7Eo7aLXe2XLDx/5QmQJO9NWGe1Ck07WuTx9787Wujuz28ZMk5hJ32JOaNr+EljXWEFvZSByjTMe6UFNXLBDQ/sKNhr5BW3AZrVmHCHrA4s8pq7ahyc/qp8KRt55NnviKDxCiWq/E=
  template:
    metadata:
      name: graph-proxy-k6-auth
      namespace: workflows
{{ else }}
{{- end }}

