{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-bff-config
  namespace: workflows
spec:
  encryptedData:
    config.yaml: AgBmJplbabGvBLH9zqvt3YANVjBPUaARwJu/H0pBx/k5FpCSASfP0vKx7/XL4JCg01+awygBW8a8t7bBChs6yXTcatXGWKeVE1eX2go9XPmwGM9OKR8cLoFlufQx++0N6HhMAOuonCsbM33X9RbmfYm5Azxontmk9+W6nQqT+7UkcpPheC2f0tFKyJVvIVbrUOsJmls1TgmQUFZIj5dWtOrgChhC6rSbogMWF2WtFpT4RRlCKZUXMggFPTw82fjytCVxDXaxnjwD2Wzj33dY9gxy10iGp/MUQefZ2AM3iMqcgu2u0ENe5dCO8bKVcaemytRuKRiK6DUbKq2pa5gATUG9pDUhbW3g9Aa7sQyjvOSun+G4S+1+n9+EMTaYcv79eVkAnl07XHe6p5T3Bsl42iZdL8gMahtFwYH31yybWFI57Q66zyIFj7oTzr8zvyYwyYj/VpAA6gMKxAF2eBXwNOhKd7LnUjI7iitBiDxIBfNQImkfcfDaAQSm84JPZW1YJl6jolvJTQAckjLMrrzDKR4X953Qv9BsPZBjS16MVg3hkZR9Db3XdP2lSQngsT/WMDSJ44X0fxNHU6Hamv2hanvYw1kCJCeESYfA+aWtAcsZtjX2axRfiuWHTxVZ5nUcTsCuxbIpla/iS7jG5i81BZu79ilEKj2rJjm6of1y5dWehZm93DQjQK++jgU8Bil9UARvrLG2hsrodpl0FTSYUMAyF2Lct3FYp9yr5juMKWNqXeK4z/2E/fX3DbQUK0vNCpUXvhwTPq0KOtlnTBbQHJanHjROI5IMe2Mtmoypzne/K/pWJSGz7b6+n5jBGZJjaOeH77+f/mAFu5M3K/KL2yxEjU55BuHnzXhHgDQxErwM61NJQx5OhJI0zLcVln593N0c8J73Ei7I5yaEYo/AVorADwv0tjWztUgCplE/4GHAgbV9Fats2dmZw90FnBpZALDOJZInujrxGze+//rex6s8tzk2xEUXIZMZvPOKiIUhp65+m1PX2aQwNOjO/v3GJUHdnvjpCk8PXAAq9l8rlyOTE1QimBwaLzIA8CI4vh/iD+dUh+TpWbs4wopJyA9jBUMCRhZLNvXuHG4bXygZc5b2OJ8Az+qMU1LpTcrLa1g7/qQHOhMv4EyoqbluMLFY8RtaeT59GtBmwvvVCkCoLDQazCxvkHRr0f/vTiKE7sG/CQ+rlDxL4DqGJsgcQYJYWYbBaykr1nOBsoxeIUBKFzJY7o8PP9LwBlf7PmKpQFhcT+xyIdOZJFSVDtiqVr+jWwTJm+iE+3WI/M/QYwmhuLcRf8M=
  template:
    metadata:
      name: oidc-bff-config
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-bff-config
  namespace: workflows
spec:
  encryptedData:
    config.yaml: AgCPELLOUV6CrV8LF+0Qpk/u2eOWo5xogRFf+HI6GCnpnXe8j7PDC5LrleqmA6byzcQWUOgBPW7pHgXATjLYyEWag5RjLKIeXrOer/BMEgpX5xJieNp9WfnWWXmy5BIMyrl6KPRmHw25XaaL4VjNhiY0DkxAFODtErixWeWAUWsZQy8zRKREdmOmGRQxQgaez/K1MZ++B+4taXRYJR1em6E6B42NolCV2C+ZiDvO2VcnM0bk2dwFDmNBbuB3/6APFN4MwO3SW3I3Le0a89N+I+eOIZMdtcU6ZR6lFd8glPKC+BQtsY8gnWla/Z7H8luBKvjzxA/ymS2JV0hKDmuPocJaFk94icTTnCCd4/fU4jQFc3l1Ujs8rthx1EJi2vUQ1p9FfTbiwj3l+1ekSMhWOIOWNrMY/UnjCBVQqpx12gGFTdQo2i64pteuIDbGDpBTOFc2cCTouH7mhtinY0KeK2OMTXaoLrFJlepMBoIawJ8ndr9VyhOgiMwf6ijKc1u17FBQa2H0Qg//GJ6E5RYkffiTW32b+5D7hL5cXQWdxJu9PAZQVhhUyGFa2fv4omRbQ8DC8442i7oi7RssCq2RTpgnDEw5uJPDs38o/o6GqGCLXFhzhU34XOtlSdQnUyPjX0Hu7f/ZoqhmLoOoFefOwmhxVrTng60QFpA5MsS7Vknk8haRPtkcfDUDiJYKUn2l6SMTPfzKGGAyUDlxtaKQpKFjcvAF35t77UUUhtDu4kEv3/iTFkJvqRdWibZqs5IHJts2OaQysOQWm6YUZe1RDdfAw5hFWDd4GKfixmLfxhWS9s4rhqNKSqm07oBhRsiZ8kumP5L80vV205F2Fto9G6uG0HcGw4Eg7N8U40+EQdD/4y4nwp1t4EC1NQu1fvUaW5+wz6zapw9JcFwbrqEdVMO0fh0dAeN/NnuKKlrgBkiqgGAb8roEWVeJS5R7P8Yb7TjLiSfFKF79VrNP8EWAe/Hyh8zZqUsTbla0whscOFASASuSK+LBj7KgqM9Qwdf7gBtEqgj74DeVVfA3FvOBufUv+gzMz35LLaqixiE0aXkaPu2gCS3pV/QqWb7T0sSbL5NpVFzedZ3dolZ7NF9toXbokV6HQhf6vlZXUXF5urfdJIeCldSPpxUE27hpQB7BqLQySWGyotAM+wKG3uT71ekGVqieb3FLCCXwU2SXRwGpee86LlaEed2QpBA55p9XmbNbs6e7X6fNMyx1mh1cYTvqxXZr0KQI+ha37qodd7Pp8n3CbG466QxaaFjVgimDLuw+xBx0r3HPwq5vu/A+Mz9hcPhj4K/cFmC82FgXjyadX15eiGh6tfzIrY/EhD+0i33kUJ/2uQ==
  template:
    metadata:
      name: oidc-bff-config
      namespace: workflows
{{- else }}
{{- end }}
