apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openbao-secret
  namespace: workflows
spec:
  encryptedData:
    unseal.key: AgAppndymkt1zzD5AtbQYuibWO51r9S/rZVmjA5aFyF8XmOd0lmOH2FDpBRy8arrGR0OGVlJ382TMD4fm77fjr5XRPCIafCFERQoBhQvspcGqbRWFwi3eWDckE2eZ3XxZykzThl1T00kElltt01mDqSGsrT8Yhq+kCErBhxYvs81AQYnSOavFIq+hfP22dT58DyOsH3Fe74ZXYjQREyfp787mpoBRCuX8Wr5/sRst7yARxXNlnKoB6dICI3V9keTiL0d8kb//byWBEnrfvraWsS6f9fGSl4U3h5alI9vjEWE+qwKE5Lkic3kA0uV/XZ005vMw/mOcP5fBOVZwDUBHiTAO2DCxkAGHufY0F8YA4RNAh8lHG/95HheiqOECT+GTnpGZPPws/2iAcDmLtuTJtMh2UVNLbqLMzf3qZZvsYlaFgJHz/eWrmZ6HO8kV7lGd1dwfA+x7MM1DZaNyMrj2QJ57eTFpKTJyMJca4xQ+sNn8c9eDCXiniPxjJMKWxugAb5XusiUPuriH7FXgKgGJmDFTiDgXM+8CPWuPBM18e7awFC2X6IEOpeYQZxVP7JGIOoXtDUzC+DxnGBmcpQ0hUykGF98x2wXIOSAmraftvcZ4/8iwKoMo+jmdLferkGGPZnLemQIfJkMRaN4f05Yl3q1ZVFSbmrD8hs0GLCuxdn0p1dl07/LbXDHB2Xzhpt7UyqRquyaszoXLLQLrEJfVlEBrbAkTpXGO0tZ284Yk3C78w==
  template:
    metadata:
      name: openbao-secret
      namespace: workflows
