{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: workflows
spec:
  encryptedData:
    rclone.conf: AgAQXude0LMDOe5MNHMEfoC/RZOLQzXK50x/dsYeoHW/ikOLEwCze0pYQX7ltKxpTB3uDV9j93ZvawTl9FRs3CTYyuO4oaFg321t94NTnpFgbFjdd9t/gqVtSsa2wZFB1blnJSnYzgBNEj0glq8hYmBuu8plYw7ruhoDEIs+DQrUMaXzffY6z97zqr4dBwV/Q1eoEntzidqrCD59hGccWNJFK//1yxWntBngx1wjplidiwuS6EsmaCmiLkcw/EllIWxoP/8hCI52Bj68ZBQMZgOFd703DQgwee6VRZs1ZMyCj9fqH4pzEtpoY4JZjVH86aMM/I/AWYOPIx7X/lHASRIgqRuykBxuXxZKaWtMQ8y+qa1ESUlSACFcVuUDO+bC+XH/a4XwwcLQITelDvzpE6ntkUN4SiGBm2sIEwkec4mAGytqFOtY6kPouC2uuBq4Cv1OMec93wz5HiXZfXt/PyKPlV6SWvyaMQXPGaL/qYrx2kkmf+YpfebrNW9SMTbiUuNr05na9XY2BNkjlbHLNhNSYrvrndoCdZuQHbMGS63e0Vz7ZCs3aIdzg85s0Ltl2RU3V2EiH1F8C7Oe0ELL/8M6ZZu/BExNTQwjdmWL8Eye06QogALc7JcOfJz0mBU3BVHXN3VV8L0oigcf4ywq8bie3OS9ahB8+BsVNZBx955TgQ1uuW9U1uqFQfib8tQf34sRkX5hAUu2jiy/QELEaRpvN0CpfRfs/kplrZhULmdW2xc/ADLU7+6aNKU++Q0iQhKSQ+FRWIAYBubyseowQNo8IMtZ9wbbFvAzKKVKaInJwXB9RB+wv6/+GsqAnp454WYsSDb2QRNqtE+GXMRTfe7n21I2ZDJ/qlJJ2WwhND2ITVNa0IZ1sYNri+uyf0dw60I7BMFH4OC2DNHvlVUj0mJsOLH3Rq7dcM862u2tIPp7ARnYnUezUD8WFMZC4DjNBDVVdEAsnm2SZBb5iOeK0S0CYM/VsNTKakHQnZJ+tplfK85R8zdyarhkD5ciSpnatcIUsY3HkXc2P7wYl10vEH0ge4i0GJqqb7Sz25rONlft0PqYwARzfZBGyucqxqrKNxdybN6wc8glEUEx6ZQDn7nW4nLbDXzutt+pL23gxQCW7N6ci798Xs1KVxursWXXpI7fMeqanZXp04OQT+Hi+2S8ugnJTmB642uSvuKWAtY+rM4oF16/RNJiezmtAZiThxTgrD56qfy+3j2u+4pLYqPoVxjmTs4/4KqsHxGdR12VJ/NmjzfsPsOaZaprbbeHgRGOdHoB718wjLEtTmzQog1kK6WcdSBcCcv22ylcfI5q414C6oIiUuCoKg6c6Q4JxV8svexAJYX2EU8LBZrBbeteObQDQNwK4WYuy2dX4HBz4KMKHkg78H9XFJ0VLwmptINVRDjgw5bkWb8IhH9OmF0ZEOfgtReUDtSP4JdNMw==
  template:
    metadata:
      name: rclone-config
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: workflows
spec:
  encryptedData:
    rclone.conf: AgBXK5fvJQNMGIfyuOez0AsC1sw8qVljYytXx7EDaVko/U9eqSzfg1PTYFD2BdfVl9CGG1X5xvURRGXRLmw+rm7+XF2NTr/L62vdRhzzPzg3OvUUrQ0pJQVw1l/mtQ1Ceauech9jJMw+OVEIk5mx5EmDFHnN2KXRf/KVrm8jRGGEubcE/xH3kdDksuHfiqEmo3oPOcxnQ7CK0VXQoSJY4bIw+E1pym/grejCfVj9ddn3jpXmuhhVa4lRR/0SR+3cGM3fUaFNuiwBhwa1ydeccn/VZxvXCcNM3MI5cPB92wIG3kic/SBuzE/0tMkZeTkBRK1SAEFtkKfF0Hv4Yn0QAYxmvqk7f2FsA0GHuVv2k3Rmz78W+2qOMBorM3i5aSBl11N9D+mG7ygmaa3qdAKKYaG2c1+o0LHEWU7SJjJlaUqSZ2vY+Xsh7Jm6Zg2MU2FGwMenJPHkjYpBwcuMXMag0d6lJgMx3kl0q+JHbS5zpyZJTPAGnt9SFA2/K30NbNWqNp3Ke3/y2TKBupIqOSCs/4AB2HMGqhi7ableHzM47ZvI1gsZY6oRY3S3sKGxbEizWlDNUf1wLHpt3lhvKIy6ViZmSIbb5x3S6aqLKPr0NqTYoPit1I8o6rTLzSeh0rMOloZr8yYeazhFmBK/AS14BFay56eB13PqeEVoII+ZEa+t+CLLE6Tksj+ru+HF4IhGr+vou2YvILAD+mbtFhd1MdFjO53KhjjcqkG2cgX/TMJZU/oaLOQaD9WFuDi9MJsH5Uk29quO74vOiFleq/HZ2+bw1NkFyB/Rc0/E41cVhzLnvjn2EW3gc5uAkZt6T/AetHb3EuC/smXbSItkRVa6Tw9muQzMbl7MvktKpRlQlB4FvQuZRWsijkzKkv7vihnVJ3B9YRrNAfov0mndzlEnLUiCc8Y+bQp8dpqkZBjo2nIu8knAfnFLeTeDXrXu8mxcQ2QJfdp5YKRDCkrgH1k9Hif1TTo9ztpfM4R/Cjy8ResK9hV4PbiOxpYg0GTjZvBmDZ6QbYJVZNukyuda8GiRlvc9yjiWYnNQ8juvbZSvijfixWrWsMSEW98hDNWvPoyFQJaiipOhuCRiSS0YeObVVPCKDyPWZtS3znwzWC4nV0b0hDF2WWq7X3FLHmiBUqaL5Qo1OTa2yjVuBAdvfweah4+vLUomduyYmpkz90589ZclLM6mXP/xcvTTrat4Lp4ZZ1RQwXy7WdNDJULHOD9bjXK+35eFmCAFgai0ItknFNE6kZ16evYe3n2M/aQWo4JuPriB6AKz4ZFU+Eb0WqGi5NNMI3Biih/oPxhQzzCg8k7Q1fp4ZioGOtWwdiVjLtvSxDzcivuHswkSqtTAyICsCTujTgjZYWHPI925BZ/zC7CnWc8r1XpdGWIjf5cTECF+Kt4A0tee1hJaM0LN7o+wJkCQN1qy80/cYlfzUOAUWg==
  template:
    metadata:
      name: rclone-config
      namespace: workflows
    type: Opaque
{{ else }}
{{- end }}
