{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-artifact
  namespace: workflows
spec:
  encryptedData:
    access-key: AgAU8kmvzjfmGr4utduZDxxix4uhzkJY/WHGiIvWFne56TcTszMl4ZWqOnPMR5YQ+Ku4vQ2/7JvV18rwbxd88pNRmn9MFHQrZ/mJStTfgvscfRkcCy64XjCbtT8NOEb9W1rwjxNRB4k2nYOBR//b2uF6ie8bMfZVzrdCPq4mrrsQHhcHoj805rAWuA7CQre7GFW0WB6ME0T6Th9O+eIXLufTsWzPwyv5YK09k+73dwWCwClzkSM205JY1M+rLultzPfZMVhIXHwiJXGZqWhmgfLxX7kf6Ao6N7QAaHk3uUubWluOeAsLEngcuCPRRex/PM0eD3TQBnjC14vyFIQy44JxMfNB8n/uA0h73mqbmEGsOsXKpDu2SLv2hXNeM/epH1WxnGoO0h0RL54XXUtF6uWKYsUxRmHqWKBlLrFPJRugmJTsci4uRXifFR6LnteSU6JW2yWx58HciFG9Zf6Zz16dMRypNWGhaEu4hSM9K/gaRYFtc7LXankInAlYT6mkl/pWIhjRwGDaCrpsmVSTHnl6Oe//MaFQA7AbmtiJJMn3v39/jLUXXd5PV9uKgk8dffR3ZbJPr+kfdhbfyUW8ZcvydGQnVM3F++6dthAEIJV/6ZK+zhCAiQpi4sFiYjwY/USpRv7Sua3skDU9OzIZmOrkT/9UMOU/Sx9upcKAvyn4rzhhtSLtA+rFqunqVBIEJGt3S0tcL/CabH0gHmScm+G0HrqkFw==
    secret-key: AgCd5/JzYnBg4vno2OQKQQ6vuprJOV0D/4xUAjCKA0DCATiwupjjVmb5qczgpCV1RpybajQZ0Th3CUsQt+dIvjXILpYNNoY7eToiZu8ahanZ7oXRhL7K+I1s9r0jXGn4LwK1OTqIVPc4G09AmwOvD94t8VXEXBleUGbOaoKLHAD9gHg22eJO96QAsQIlMYlQ5zPqUUiyfcdQHcClCYUd0iv0xr1PU7Fki0bhihpBNU/eyWHoyFXrFecNwoJtUSiJbNkwPTO66auWAXdBYXZuBQdUrc4wiadVel1lA28aoQglRTOCcfydspRdGN8svjJEkJkECeSEsf6HxAxccRRVW20ocm+eKOzSTZh87oOZ6uAiSS2EzYpjfUdM768KK0M0eZOzeYZByAp0oQ/QI4AhI0IZ+PboncjHxNSmwSZQmBOch5ulrhL9VJHxSxM98yETbbFkqiXh9zrKCiGk6OMOFaWcGYIBbr1Bbn+tnVzyHyE0JcC5ngQ5BKen0h7X4+dPIFODp/gx34D452ijtWoDSUMqZYNHsTs07O6GeMMBJUBYCfZ2QBkQVofIG+pgG/wKSQOBsHSUggH530zjXOk5h1FFGCQYV3oQdIJjouUz6o5384GDcCn0tPXiHVKFrQFhKLGsikh2fKvlzwrGf6k+yc8aH9zQVRcvRi6vYfxwzeytjQadF7UIYaUeITRco3v/Vdu5jgRBUjMMyYvJLIx+KHO1OcYE4LbwqAa0Oa58uKbESiqJ7VacQe0r
  template:
    metadata:
      name: s3-artifact
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-artifact
  namespace: workflows
spec:
  encryptedData:
    access-key: AgChCeavEfCWI4YQznB5oVx6c+2hzI7ANiZEnJHapBZDdYhW+/Dp+BnL13CuoHctgT4I3U9s90EeVlXzXt1GPc69hN0yLCeu2F0EhfIe6TVUd74Eskgft8j1h9ntWCjep8gpwbwrtY7xMJ+KvFxmv62VFJMqcTVdrYKAve7FFkbM46vC3mKAxW5flZyUTKUrGY9qdESBHf2iCMevERLm3w9Zb9gztQUZv/etU6SWokodGZ2aVFMg8n5THjxNRTqmCD+spbz4MNQVw3Xbbe/0i+OMBL5qA/z3c3f6DN57vi641x5m1TRZN/tPGggaAYx7SAQiwYqrnWhNHWmC53VM6llq3CGpDSJnIVEShOf2Orte8Ug9EOTPFgxfDRITwymT/E3qdQf/Ok1xDL0/JH/jOD3fjiBnhAtE6CbtvwWK0fJ2afDkA3v7WaVFNxItW9rroVrZc+I9Lpl3RukEqbl2BzjmWq+6b3Evo197hFcJfB4P52oSh5dr7C9g11lknswhWttZiTlp/e2LtTqGZHw0mHZspHah0oLNLrV03EaHA0rH2HWLHF9DqnykBSiF8ZkmrpHQMbemul61TMrj3n+AXYl6xQG639umPv576Cq2JdYL3Nvs7gQ5CzVVWeAMAiceLndSudho0WxJCVOplll+TXHMBKrsUQcE+OvUNlbIG0pPAQegzIIu96cZ11Jl+PfSS6tqe6ChRo8ng03LVDuBxHuPW48flw==
    secret-key: AgAkWli7k68yd2zm0Ofufs2Y3jRkT8rnYWAN5HjmzImSPCcusUlBqCKI4NpDZRsobq5j/Fi9i0xfSVq+qPASpkpICEFpgSohBOrmuUGJKy1TIddPhkLL6oWc3QN/4KMsFe10ULa8CoZjuI8RVD2fXnQU9OJwOhUsS9mLMfiiEVvNoktdf8o0fBY2ZPtHtoqD5iktV8hJLhyLDYjDOXc9qr09ole8hK1JJg8GWoIr3WBhkC9J9H4RW+gt6Fvjq6OdJve2XxiKF6zjDnhoERA6CvcqiNsFhJzGkEDNj7hud947pJwPPr5IrC/wMuntCHazK+hVNa0p13zGPRB7rgT+8EZJaVS7qWP1kxh76jKyAN8CpCt2VanISyUU1KLAt2KTbITrPsQ76ID1XpCK5GdEZ5MKN5xdBkS41vfT8eWguhJ5R9q1+lN0fVwHxjwKj2xxkyqNpB21qbNVsm3rcc27GmkBPKuUjZfVj+8rFQaGTHAQcaOdBHYQafcXzqW8rGD1qkylfFTiOFHkocagXNPqvYGKk2OZPhqcPt0az4AURza7gZbXcz2k1koAyyrvGjrtQyW41g+0g3X0lH3xd9T9yRuXrIlId3PJV7zWVWbEpu1NtwwmmsUvLRF69yi2+YKXQwYeZxuDm2Ns0+oMngk3xzOg2c7+r2rwN5BLjUQ0/Q6+9zEVrmaNSCHUE5A7+FtT9Pw5XKBg9yFWeRnAn5WnPk1GCjBlsT0kO1y8ybEryBZwfpUgwRtCj8Ro
  template:
    metadata:
      name: s3-artifact
      namespace: workflows
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-artifact
  namespace: workflows
type: Opaque
data:
  access-key: dXNlcm5hbWU=
  secret-key: cGFzc3dvcmQ=
{{- end }}

