{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-alert-webhook
  namespace: workflows
spec:
  encryptedData:
    slack-api-url: AgAUG8ZRsintvELTmMukDH6dvPCExHRV/VglRamEEfIeSKNZahxDdu9TKv17RE4hJ4XK/jN0fLrasEtEL/WZaFaxueQIxHDaEM4i3VBGEHptGvR8TfyswVOgLZDDXo9K82yEoRkrXP7BO/SGz5Xtwt0DLdpsCFn19qlO5iElEhp+aV8owJvppxc7Kvj2mRIdmsKAIWRQSbwgmk0SMpA9lJihnRovNgoc/RexCiqTDdvkJoT5al73bUC1L/3sKvt0izRbIUW9LtUwLfDne1uxo4gy3oCsXnhcXtdN7cuAU4O/8z6zdaN+J0zp+ZHgnQ0WFUlervAs8VHKn/nJCU3srKJlMfw/eufbfLjvPgQD1f1vfKDySwNKleILbEO20jDquSL75noms3/GoKJj0bLMhN7++e8OJYhGdTEjDBd//jWEByZO4iMORO0AJip6/Dlu5DNsY80Qv8u5ov/DxMVRaBVANHObHAYR+t8HXADDSpavBmIGPvAgnSrBYCu1eXJDtd241WxZFkAV/PCOOidnquDMQr+LeKMK+uFU+eAQJEQgp27zBSQaZt/XA6ouwgRVEmSWH5QlW3L6iGuGybwtbGKSmyJRUTMEJ7nqXqCJxvxiGId6CHekcu+s2wOESUiD7Vcjxc+bQExaVrkeq29khFb8Fg1eqLvEcH5MKwum8IbVmu7HbFCzNNJ8HbFT3TTOQEDkcwXxs9rMa/F3Qn7bnkMR4bGzbcElKyidaPfqNimLPDe0Lobu7HOqCqoaXpP51aq54VlXd1+IkZKx8vkL9CUkKAi+wS4N0zAAgcvVDwPx
  template:
    metadata:
      name: slack-alert-webhook
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-alert-webhook
  namespace: workflows
spec:
  encryptedData:
    slack-api-url: AgBPYe9fzRoRhkzsccAMCiBle8I6Igue01749dPW6qsD/+c7yTn+ycIo8mQ4Hh8nh2J44XVaZ4+GKHi4g4fYLXAxvmtbBi2rkKJw/d+6ivuKESGVXyppWuy3AJQ2fTe3kRPcXZuNXPkzuqaMi2WedoGZYVDxzYlu79A4DtCsFG1PnnO6N/8JKaEp1H243FqxNcGUPEx5VD1auTUbL28w8Axx92Mn7/pvB8U+Amlct6L0ZPZOOoiK6j+VZsT6Bp/joRW8wHFSHCKaYUtxozdnzX9B/mMua9a4XuDrsG1cS9dXoQmtp+Y7FKcQwhEoU09BdKk7jDJ/dEaiy+Fp2KoCeuf6vrlIrK7LeSmu6mJ6yXkseCEntrMhj9FzzEIEi7sBwocN8ydIjrhj79L7SP4C5ZFNdcMvauYlqMCAzEzGSYQutr/UB7v1g61UPgGY4ujVr4kX9dKoFVAxU0GLup89qOiZG8hSTrWfv5uVz4x7LGXPTO77H4rjMtqKyvX0rhS+/Aua5b4od56V/q/ffbAvL8wwghlDTDJKbAwxhIIT1RCfBVnqtiCjeGuBIL63niAS/5U5rjcLN71c7Io3BTsFKg6DWBA4Tr6KoEIB+ZkLsVurUHLo2+z2UnFylLYaU2f52c1bjHO95fl3F97N1sbq2LMo8vY2R+LLJ8CQeV4/jko6WUH1V5T3JK5hb1WU2FQzJjGBgHWylY1A4ywOcr4bEQDI5oGo0udfgdm10ozJ1YDTiA1ZepmIIPrjyYRcyM5PFJe3YJuedWM65A==
  template:
    metadata:
      name: slack-alert-webhook
      namespace: workflows

{{ else }}
{{- end }}
