{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-alert-webhook
  namespace: workflows
spec:
  encryptedData:
    slack-api-url: AgAUG8ZRsintvELTmMukDH6dvPCExHRV/VglRamEEfIeSKNZahxDdu9TKv17RE4hJ4XK/jN0fLrasEtEL/WZaFaxueQIxHDaEM4i3VBGEHptGvR8TfyswVOgLZDDXo9K82yEoRkrXP7BO/SGz5Xtwt0DLdpsCFn19qlO5iElEhp+aV8owJvppxc7Kvj2mRIdmsKAIWRQSbwgmk0SMpA9lJihnRovNgoc/RexCiqTDdvkJoT5al73bUC1L/3sKvt0izRbIUW9LtUwLfDne1uxo4gy3oCsXnhcXtdN7cuAU4O/8z6zdaN+J0zp+ZHgnQ0WFUlervAs8VHKn/nJCU3srKJlMfw/eufbfLjvPgQD1f1vfKDySwNKleILbEO20jDquSL75noms3/GoKJj0bLMhN7++e8OJYhGdTEjDBd//jWEByZO4iMORO0AJip6/Dlu5DNsY80Qv8u5ov/DxMVRaBVANHObHAYR+t8HXADDSpavBmIGPvAgnSrBYCu1eXJDtd241WxZFkAV/PCOOidnquDMQr+LeKMK+uFU+eAQJEQgp27zBSQaZt/XA6ouwgRVEmSWH5QlW3L6iGuGybwtbGKSmyJRUTMEJ7nqXqCJxvxiGId6CHekcu+s2wOESUiD7Vcjxc+bQExaVrkeq29khFb8Fg1eqLvEcH5MKwum8IbVmu7HbFCzNNJ8HbFT3TTOQEDkcwXxs9rMa/F3Qn7bnkMR4bGzbcElKyidaPfqNimLPDe0Lobu7HOqCqoaXpP51aq54VlXd1+IkZKx8vkL9CUkKAi+wS4N0zAAgcvVDwPx
  template:
    metadata:
      name: slack-alert-webhook
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-alert-webhook
  namespace: workflows
spec:
  encryptedData:
    slack-api-url: AgBixUIJej+v9Z0xXJ7+8PjY0rQcEP1zbJ4nV2UQHb0H2yytYuOoZFL5/CmQCbrnGWKJhbJ3SZLde+6qJK6jH/wKvzUsIVs00AljNNA/wiFhn/9piIz1xjrNjdfsztqePgxRuYI2PqwNaA4mLN9MCJiBjTUOL39+IgRU+IuTHTHtxFOWeYUGwv2sqRzBDa0EYMvi806XgkEU4y9g4IjCD1HylhYcPFST90MGhPZhax2ZIDq6BQqDz6jW8MaDr/l48uPEFv5l4XMQJYYsWuDnI9C3Kq7WLVlNJmqi0rbQscRV1vKjAbZbUP44X8RceuhQpJ72hpWgnMPgqwOxyOzycXw3dv1G6rvsnXPVgY1ou3qn42VR0FYa/kjZdHCNzF4yqy8rnF/WaZJ8hnkH4jXa5a4aUd/hDaNS4MmArRBtvNxrzGN43OsBYrJubyTm2f11wAsEhzQrCQ+Ch+Iw8gYxBW1TH/bM7gIivSO+huQhOYOnqG5ZVPUfZl+QlaikV6wdCsaHU3db4haYTRKWXb8z9CzSEPtnDAxHdRsdkjJcPZlkGmXhtW7TkcjnDuOIQPIWY/XQm0tXkIWL6/d4b+Isr+gyffY67DCyrT4QEDGMGdo9hll4aDwtzkKylBfI0Qs5ZxO2+2QZ+hLuzI1hEjV6/lWKNDtTJsUZsNcSbSn7o5+p0luJIEQeWtoCEWLHgUeffrZxNBk/J3sVlUoKyoWItGS/EBBu3NzUeoPrfDaGpckIAHLyf+ZuemhMm9poyE0SEsYkHptfBi84QrUbJE2zCZ6rVyu35azSHXprMZQnStOS
  template:
    metadata:
      name: slack-alert-webhook
      namespace: workflows

{{ else }}
{{- end }}
