{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-alert-webhook
  namespace: workflows
spec:
  encryptedData:
    slack-api-url: AgAUG8ZRsintvELTmMukDH6dvPCExHRV/VglRamEEfIeSKNZahxDdu9TKv17RE4hJ4XK/jN0fLrasEtEL/WZaFaxueQIxHDaEM4i3VBGEHptGvR8TfyswVOgLZDDXo9K82yEoRkrXP7BO/SGz5Xtwt0DLdpsCFn19qlO5iElEhp+aV8owJvppxc7Kvj2mRIdmsKAIWRQSbwgmk0SMpA9lJihnRovNgoc/RexCiqTDdvkJoT5al73bUC1L/3sKvt0izRbIUW9LtUwLfDne1uxo4gy3oCsXnhcXtdN7cuAU4O/8z6zdaN+J0zp+ZHgnQ0WFUlervAs8VHKn/nJCU3srKJlMfw/eufbfLjvPgQD1f1vfKDySwNKleILbEO20jDquSL75noms3/GoKJj0bLMhN7++e8OJYhGdTEjDBd//jWEByZO4iMORO0AJip6/Dlu5DNsY80Qv8u5ov/DxMVRaBVANHObHAYR+t8HXADDSpavBmIGPvAgnSrBYCu1eXJDtd241WxZFkAV/PCOOidnquDMQr+LeKMK+uFU+eAQJEQgp27zBSQaZt/XA6ouwgRVEmSWH5QlW3L6iGuGybwtbGKSmyJRUTMEJ7nqXqCJxvxiGId6CHekcu+s2wOESUiD7Vcjxc+bQExaVrkeq29khFb8Fg1eqLvEcH5MKwum8IbVmu7HbFCzNNJ8HbFT3TTOQEDkcwXxs9rMa/F3Qn7bnkMR4bGzbcElKyidaPfqNimLPDe0Lobu7HOqCqoaXpP51aq54VlXd1+IkZKx8vkL9CUkKAi+wS4N0zAAgcvVDwPx
  template:
    metadata:
      name: slack-alert-webhook
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-alert-webhook
  namespace: workflows
spec:
  encryptedData:
    slack-api-url: AgCVcbrV3sULQs3ja9LOpBYhilbjizBl2WXQiNFUsrrg8TRZgCL3uDkWng3qHSihVl3Fo5cP4RIpqcHWLbkn+C4/kegb7d6k8dAcYpuX3pKPGAqKBijnJfEgIgBJwgqYc7Nk5PqGDRLHdRWQn14oAeMFiDz80gUQfY9yJnDBLj9NbxtZb6MeIsH2oYRUC5fhFeM+jhfo3lTjMOwUHhBVyndnppQFk0wS4x1CDzhXEqoha0gDiVy54J+uxLpfa+PPvhhVNm8m3lllMJxcMsSp8FIfTpN5mlc7vNMLxmvDU3kN+u4Psm7Jb3hrTv14UjkmEPingZxfTltkbq8io5DSxViHk41WS3shnMF95loBSocRDbjr4CrsX+i1bDCi+dsDnyerxdQiXGzuSGyyaKnMZ4n7NEniT1jFd8YgFCAhC2iLUyd5l2vQQ+vQpE3asbvtGxa94j8mn7poNqd55hUjuAnk6tRJMcxg7fTLPwGphp5YM+rvU9pc7lb1VeNyuhOzUMnoCV9Y69dDABque9OUavH2qg55Uwc0u+63jjc9TEzBRV2haA01TqV3wWFnjX9cNZ+2BJ4AbdEqxwYqWHNyhny0bY2CfAQKp9VDzSeMDLa8Y7/ujwlfsrGF1FNGqJxhy2f0fysy3E7ueqhbIf+g3HA8sSL3Sve9tLedMDnLBubuMHl3bYzL8y0SLihzG4O7+jnhI/1riq7rNNIeHtA+dmjb50llrVWwoLM4pbDxZPv/f8r8jg9MwKV3MhFk6Ntc1Ngymcx0WrORLE98EHAhnbCjfzsd4hp9hk+TN9nv79mr
  template:
    metadata:
      name: slack-alert-webhook
      namespace: workflows

{{ else }}
{{- end }}
