{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-bot-token
  namespace: workflows
spec:
  encryptedData:
    token: AgCaQHW5vxQeEwSV/GtpPLqDgczqHO23TIAJreVa3dNYYGsy+BFOwDq5BCXrrbdsE5FMN76SsJPRiRVNmi3H8eQfnRX6Bogw/5deeftpvLCTJ+pCqA8AMJ8IxbwWdhmxBwQF9rUEW4JaYlXduB9xjtj1Du27CoXxwUkR0DvMOVa3hrca8zpTCr0gC11hyBrWyQjEQCWPhcqCNvlQg2w54HepsPcG4WJ4v214ebgAlNlr0xKI4z0SrWOkFr2qxJ55gcDYyzkuYMu/mltlxlq9qEEI8QvdALl72k4QndHzYoIAtGm57N2mNwjHjqlSjFhqWp7EyXgN8cMLpzCPcRgXCDExDLUSNTG+XRDawBRQWn5U1BGyRabHI+p1x2ChUsjRvJAZXeY54FlBDsjRKHe7LubnsEjLOT1Ld4Q2fgVtevmo9X1DNCvijHdS9Tn39TV3/YzsuVrwIliFo+Y1tJwVdRrzaQQJGzF+gv5DM4opLWt618pycMdKYfvfygNNeLbXzfC2oEc/lU893QG1LuoE1WcyMxezTGHccgLRR8QpAsXQrCP6fgtBAkhGTONeo8Oo7vLvYFtnMhq+JdB0+TTeU/lZ+nDDXcw9T7klpaTp94xKHRcsMo871nihGDuOASuIFKGgb/UAUiaQVJuXyUHenkO2CcQGqEPaUP8+a0KENXyJx1CmfF6p4SOtjgpOAWxeYsqWKgQRQBSKkcST+jwX899E+mS24w/riBHfFBbJ1XC3cUJjuFS1h5eejpmLTxXKZ97iNLCdk0SN8A==
  template:
    metadata:
      name: slack-bot-token
      namespace: workflows
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-bot-token
  namespace: workflows
spec:
  encryptedData:
    token: AgA1qLIDDbR7CJIW3a5dPmmXZfsXe5DtJ1U74iG2np6a21BIhkd1NDjSNtjs096BLCiLwA0MwZRmJHXGejQSBMULESJGsyboUFVpdd5WfUgg5Yeb2EcwekVHolME3ZV+fIxc8+sv/zgXB7dWhZNhvHtdWavn3vKlgmfAbZeR/4R3nvM+FdUFHNZs4RQvMilczYSk6Ga1LWNQkGfK3BIXbt3zh1ArflYUhwJuPTv2CVpTPKoV5D+aTw5Bbf38jC8p2+BqaHPT7m6+ozFAY1CpEdNL5i8FAvRsUJZAo1LIgDP3SBwC+qd4gF+ieezb1CKi2y8e6TvqdQ9Q9CqvMJdxzw3jgi4Bad0Xv3gfhshJEs4Dbk1+cib4SRJK/R3907ClkvhbHNT5vTKhzE5OgxO3VSWPYzUtwM+vaET8Z5BpaCg30MjLr8EqL7yCYar8nF9neg/ExNWOiRNrqQ4MiG8TVpCH0PBiWDTEBrJcroIO/zq5l40D3ujkvxupoZg/hpy9WH5NbPhVQGIzdPMIpPs1z7V2leWhqvjX1e8Xea15L7XmOpuqMxffsDdiHSeqm1RUeIRmOZTbcYcps2KBvyE3bY3SeQd80dsg9Ak5Z0smiex2lmhhVAm/sTHtd3VPwbzCPBKECPl/8x/ohOvE8qVTjXqosjsRB6wVqibBstBGYyv8sEw9aSWlGYlRRd+BBzTRPEaGVcEHk60LJYn5GNc2e5sIjISmboHAr3JoH2MbfPME/Si4VwUK4P+HrplPxhrbUP0epBI4YowYwA==
  template:
    metadata:
      name: slack-bot-token
      namespace: workflows
{{ else }}
{{- end }}
