{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workflows-cluster-client
  namespace: workflows
spec:
  encryptedData:
    client-id: AgCf3l5mdEO9G3f/Re2tBg78tXBHeOe6kdHCAwCVOA4ehY5sCPfgD3kMyvgwVq5lk1ljYVmruFk3f1eycnyTyMNeBarFY0Ecr78RdxhIrUhTnS3I8j9G8nlqOsuEsJ6ITbBQpc3+amtAl2TDgQRFFpfS0iUNBngAUgRaqTGcygKEVTg+f4wcVjAqaU1GeRfs7k2LTpy9XMUsDZipKgjacSeP/vdLIl+HttNstcd9crYg9B9SevUUQ5rlLvNMznGuZU3y7trufx4wVAmPCPWlNRdu0bosHN5U0/joDq2/WAnYmiQIPPcrZCZXGoF7ZcXJPSiG+fh66JIBOHR0vga8V7v8n0JnkZ+8ssriZNY0mueKspasPKJc/G21uw1qG/IL5nlqDYaK71wdJFjn6/7a/VFKNXQwRu/qwc2/dyy7302niVIzQp2tmOQO2GKT5ELsZFR5bob+9OHTConKBWoBzsy1F50FYZUvqpYn6emcuae7LFrF6F+T4sc+wIGvoeUxEvJPZmoddVMKz6Wb8pttwu+oN9pmEDUr3b+PtdwRr0rMqfOLjJVER98qomcbkSU3v/OksdKSERt8KgvJ04x07ffSaR9Vd7e6kPtOBwcmlx/KyZkos0Z+W+25KLj3rvToAoA6OkP9LxLSu2dll76LwO5RyYrv835wWux6f4BHFiPwls/eygqPEbPS+0OYSgj4EbHCQMMRFWemgPksHgw/4Sqmyg==
    client-secret: AgCsfQ5tMaHwczRZKyDlsZ5Y1vT7Ywlx94EGRQouB8h2ugnbQpIG8W69QRPAGZsdXlyIYthkTSOPTICrQ5We0xMEG5UK8sIbwSRBHveK70ptrueleypMqESST0p3eRlW2aAMAkpJ/BoY4Pl8rh/rVZ1kxWQEQUnMottMNwJYuH/BKmqc3IU8LYCH72zRL4m1YfBRzWhvrAY8X5b0qIan56kFZGaa9U2k+SRK8B2LYzFxxwXW7tU6BipVSTVxjy6Ahxey4Lly9DauIRCZxOGMubmvDK15NTAoyRZ0rlyyTZXnmWdyjLA8xoZLD1LnqWWrK0PG6TUjTyzyf38EsRNExmeL02mKHXXRzQPAQad4jvbWi/a/ICG3DS1xctDi/UP3sDv9rvyt2jgbHoCOXboZvx3VMqgHQ0KAZcu60nXhInxQIXJ/8x3YvHr96hmcVxIYzt2uc09M+m0yUQVBYbZBcbcp0+VYYOXl34IQJylvwNoVnYwOIP6+rjHluz/e47rPtrQR8ZsnuGFaDFQ6xJdM8KGcT28baLKEpV05otbLhTy2O/xTQ2doy0t7xGHf1TSASTQc4dc9TdpHXc65yTr2DZqzdXk/V71pDYD3xaFORSdnZAzVJ7WP8Po3nPuQ+QVIA3RtNAmsx17dqJdukyZPEpfQ9ieh/uFJG6UneWm75WTrp6lx/9UEZQC+mPPCSPN1TvN9SjkKZrl6UCdbdvsfQeyHh9s861C+hyUuIZm0zK97yQ==
  template:
    metadata:
      name: workflows-cluster-client
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workflows-cluster-client
  namespace: workflows
spec:
  encryptedData:
    client-id: AgBeCSi4T32dNQcS+o/i26oCzPFkVFMRGahOJqXYtVS5OtFempNT+vE0wui7xItBjCwPERAwZNjCrE/AvvM/s1xKc8dCp3B2OotiWc0Ab2A97bqAIjsFsRiQ5KxG9If2tY9cDUxFROeCh6nEOHX72mGEdlEXTjEmjv8pJ6c3jhf5O0Ab/Ho5ZBYTd/xPTo9biDm0Fc2ikvGi4Ak3ttL4bPOPaEr+47eGJPsfB6GT+rCvShyroeb9t0tnzbs0Q9j6aWJVs5Q1cJm/Zr3rNcE4slyLLrEwCAa2bujevX5FLm453jBkJfQpt+6v2MmXf8cXZjfog1uY0wUyoDHT47VoUvVH7ioNAGCQlnRS6M0/KkDdSHy1W2ZepUG2Vk/gVS5fo+I5cN+SPrLdfQeuJyDIqljUdcAStZSyQYGAsOsTUS+unJ05fyfa3oByVYOzi50483IMnf2cUBmsJvKkD4GBSq/TACmdON/AqfIwYEgm8REqwGnSDg2RND1MegJ0dUGXC1VaILmQCTdWJux+LsTV7jU6ZtOPk7gYc90CgH4safG/pP+ndL03ldM+F4U+EATealclYBPIOarj02JBVD1TPJEKBFB1GQ9AWlFEfzK8QgP/BmAcrewk6VaGApiznl+JB64YiMy8nB4AU0U6a8t+jygBQeAy+do21BFHZGzcQjbJtjPw5Tw3lCPPpS1FT53uRBNZkB4gnBrI8gPpqJ3AAErU+nGC8Uz/aUVR
    client-secret: AgAD/A10mgQI1fvl8GwikDnxs3y4p1OqxEtpI/WKcO6eqPm/Ki3hyFKwOi7HcbLgdM88JQVOADGuJRaizV29q0I0BYou4d/Ko+KZJ7WJBF4kff8MPXR8zClXg3TVFJ1uIgLagdr+cQjiLcibBZz+Tms/Z0X0JTMhl5qfezHBLT9oCnu0YkOxZdF/k9xQv5RBe69gyWznqUQ3FsuBcYQSghKrr/NCmom3weGSayjq8WoPv9/VndaGvVqxyjgYRhnwwDcCl5VoHsNEpW2fe5a3C5Ono0wLfn7q7mhiWo/ABLiqFdRalBcHowi37eIhGN1MGDbPPnT3hFyu/5o/C69O0kFG2AkCuLwbr+NHb0atEdSfgNqxqiWIxOExthunU/YmKGmxPJfRlaGO/MmcOYp2zu8kQhbwJgpzuSeyaAJOVmpsznrtsRsPV4BNNCfQPgmvD+tXNiNlmzB4rjBMGQHXJQAQXZnLSx4HnYAwvmywfKa2k0Rdq0DKDgq0nMtgJDhnpxYSGLor/gxby5Achv1ifybWYynXbT/hE9jbeIPYMQaCmmgDL2IU1CCD7K77zoAnE1KuWYbXCuCnCKS3f6qbeL+aobtm62OvuYQ9IGzJuPPNyh+HSs8EP6tdARV7RFxtoyA0bDm0V51DrPZkPz7AdAO9mzCQfQ2tFOiZbGW/dkLrQMf/o3O8gDikjblckyeMZGdoL+VtRG0LW7p4HwxzhNbZEp7XK6Bxe9ZMGaw//0oP6w==
  template:
    metadata:
      name: workflows-cluster-client
      namespace: workflows
    type: Opaque
{{- end }}