staticSessions:
  enabled: true
  sessions:
    - data_directory: /dls/science/groups/das/workflows-platform/staging
      proposal_code: ks
      proposal_number: 10000
      visits: [1, 2, 3, 4, 5]
      instrument: t01
      members: []
      gid: 123456
      start_date: "2024-01-01 00:00:00"
      end_date: "2099-12-31 23:59:59"
