apiVersion: batch/v1
kind: CronJob
metadata:
  name: identity-mapper
  namespace: identity-mapper
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: identity-mapper
          restartPolicy: OnFailure
          containers:
            - name: identity-mapper
              image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}{{- if .Values.image.digest }}@{{ .Values.image.digest }}{{- else }}:{{ .Values.image.tag }}{{- end }}"
              imagePullPolicy: "{{ .Values.image.pullPolicy }}"
