apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:manage-user-identities
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:generate-resources
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
- kind: ServiceAccount
  name: identity-mapper
  namespace: identity-mapper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:manage-user-identities
rules:
- apiGroups:
    - "/apis/useridentities.workflows.internal.diamond.ac.uk"
  resources:
    - useridentities
  verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-mapper
  namespace: identity-mapper