{{- if .Values.authBroker.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-broker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: auth-broker
    server: {{ .Values.destination.server }}
  project: default
  source:
    repoURL: https://github.com/DiamondLightSource/workflows.git
    path: charts/auth-broker
    targetRevision: {{ .Values.authBroker.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        {{- if .Values.authBroker.extraValueFiles }}
        {{- .Values.authBroker.extraValueFiles | toYaml | nindent 8 }}
        {{- end }}
      {{- if .Values.authBroker.valuesObject }}
      valuesObject:
        {{- .Values.authBroker.valuesObject | toYaml | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
