{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.destination.server }}
  project: default
  source:
    repoURL: https://github.com/DiamondLightSource/workflows.git
    path: charts/monitoring
    targetRevision: {{ .Values.monitoring.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        {{- if .Values.monitoring.extraValueFiles }}
        {{- .Values.monitoring.extraValueFiles | toYaml | nindent 8 }}
        {{- end }}
      {{- if .Values.monitoring.valuesObject }}
      valuesObject:
        {{- .Values.monitoring.valuesObject | toYaml | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
