{{- if $.Values.localSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: artifact-s3
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  access-key: {{ $.Values.localSecrets.artifactS3.accessKey | quote }}
  secret-key: {{ $.Values.localSecrets.artifactS3.secretKey | quote }}
---
{{- if index $.Values "postgresql-ha" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-passwords
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ $.Values.localSecrets.postgres.postgresPassword }}
  repmgr-password: {{ $.Values.localSecrets.postgres.repmgrPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-application-passwords
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  usernames: {{ $.Values.localSecrets.postgres.argoUsername }}
  passwords: {{ $.Values.localSecrets.postgres.argoPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-argo-workflows-password
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ $.Values.localSecrets.postgres.argoUsername }}
  password: {{ $.Values.localSecrets.postgres.argoPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-initdb-script
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  init.sql: |
{{ $.Values.localSecrets.postgres.initdbScript | indent 4 }}
{{- end }}
{{- end }}
