apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: workloadpriority
spec:
  validationFailureAction: Enforce
  rules:
    - name: standard-workload-priority
      match:
        any:
        - resources:
            kinds:
            - argoproj.io/*/Workflow
            operations:
              # These policies must apply at UPDATE as Argo Workflows may apply metadata after CREATE
              # see: https://github.com/argoproj/argo-workflows/issues/10138
              - CREATE
              - UPDATE
      preconditions:
        all:
        - key: "{{ `{{ request.object.metadata.annotations.\"workflows.diamond.ac.uk/type\" || 'standard' }}` }}"
          operator: Equals
          value: "standard"
        - key: "{{ `{{ request.object.spec.podMetadata.labels.\"kueue.x-k8s.io/priority-class\" || '' }}` }}"
          operator: NotEquals
          value: "medium"
        # Do not apply to Running Workflows as they may have created pods whose priority-class should not change
        # Argo Workflows should have applied all metadata before a Job enters Running phase
        - key: "{{ `{{ request.oldObject.status.phase || '' }}` }}"
          operator: NotEquals
          value: Running
      mutate:
        patchStrategicMerge:
          spec:
            podMetadata:
              labels:
                kueue.x-k8s.io/priority-class: medium

    - name: live-workload-priority
      match:
        any:
        - resources:
            kinds:
            - argoproj.io/*/Workflow
            annotations:
              workflows.diamond.ac.uk/type: "live"
            operations:
              - CREATE
              - UPDATE
      preconditions:
        all:
        - key: "{{ `{{ request.object.spec.podMetadata.labels.\"kueue.x-k8s.io/priority-class\" || '' }}` }}"
          operator: NotEquals
          value: "high"
        - key: "{{ `{{ request.oldObject.status.phase || '' }}` }}"
          operator: NotEquals
          value: Running
      mutate:
        patchStrategicMerge:
          spec:
            podMetadata:
              labels:
                kueue.x-k8s.io/priority-class: high

    - name: low-workload-priority
      match:
        any:
        - resources:
            kinds:
            - argoproj.io/*/Workflow
            annotations:
              workflows.diamond.ac.uk/type: "test"
            operations:
              - CREATE
              - UPDATE
      preconditions:
        all:
        - key: "{{ `{{ request.object.spec.podMetadata.labels.\"kueue.x-k8s.io/priority-class\" || '' }}` }}"
          operator: NotEquals
          value: "low"
        - key: "{{ `{{ request.oldObject.status.phase || '' }}` }}"
          operator: NotEquals
          value: Running
      mutate:
        patchStrategicMerge:
          spec:
            podMetadata:
              labels:
                kueue.x-k8s.io/priority-class: low

    - name: validate-workflow-type
      match:
        any:
        - resources:
            kinds:
            - argoproj.io/*/Workflow
            operations:
            - CREATE
            - UPDATE
      validate:
        message: "The annotation workflows.diamond.ac.uk/type must be 'standard', 'live', or 'test'."
        deny:
          conditions:
            all:
            - key: "{{ `{{ request.object.metadata.annotations.\"workflows.diamond.ac.uk/type\" || 'standard' }}` }}"
              operator: AnyNotIn
              value:
              - standard
              - live
              - test

    - name: validate-kueue-labels
      match:
        any:
        - resources:
            kinds:
            - argoproj.io/*/Workflow
            operations:
            - CREATE
            - UPDATE
      validate:
        message: "Workload priority labels must match the workflows.diamond.ac.uk/type annotation."
        deny:
          conditions:
            all:
            - key: "{{ `{{ request.object.spec.podMetadata.labels.\"kueue.x-k8s.io/priority-class\" || ''  }}` }}"
              operator: NotEquals
              value: "{{ `{{ request.object.metadata.annotations.\"workflows.diamond.ac.uk/type\" == 'live' && 'high' || request.object.metadata.annotations.\"workflows.diamond.ac.uk/type\" == 'test' && 'low' || 'medium'  }}` }}"
