apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ .Release.Name }}-posix-uid-label
spec:
  background: false
  validationFailureAction: Enforce
  rules:
    - name: apply-posix-uid-label
      match:
        resources:
          kinds:
            - argoproj.io/*/Workflow
          operations:
            - CREATE
      context:
        - name: triggeruid
          variable:
            jmesPath: request.object.metadata.labels."workflows.diamond.ac.uk/triggeruid" || ""
            default: ""
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              {{- if .Values.uid }}
              workflows.diamond.ac.uk/creator-posix-uid: '{{ .Values.uid }}'
              {{- else if .Values.allowTriggerUid }}
              workflows.diamond.ac.uk/creator-posix-uid: '{{ `{{ request.userInfo.extra."workflows.diamond.ac.uk/posixuid"[0] || triggeruid }}` }}'
              {{- else }}
              workflows.diamond.ac.uk/creator-posix-uid: '{{ `{{ request.userInfo.extra."workflows.diamond.ac.uk/posixuid"[0] }}` }}'
              {{- end }}
