{{- if $.Values.policy.create }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ include "common.names.fullname" $ }}-pod
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  background: false
  validationFailureAction: Enforce
  schemaValidation: false
  rules:
    - name: pod-securitycontext
      match:
        resources:
          kinds:
            - Pod
          operations:
            - CREATE
          namespaceSelector:
            matchLabels:
              app.kubernetes.io/managed-by: sessionspaces
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                securityContext:
                  runAsGroup: "{{ `{{request.object.spec.securityContext.runAsGroup}}` }}"
                  runAsUser: "{{ `{{request.object.spec.securityContext.runAsUser}}` }}"
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
            initContainers:
              - (name): "*"
                securityContext:
                  runAsGroup: "{{ `{{request.object.spec.securityContext.runAsGroup}}` }}"
                  runAsUser: "{{ `{{request.object.spec.securityContext.runAsUser}}` }}"
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
            ephemeralContainers:
              - (name): "*"
                securityContext:
                  runAsGroup: "{{ `{{request.object.spec.securityContext.runAsGroup}}` }}"
                  runAsUser: "{{ `{{request.object.spec.securityContext.runAsUser}}` }}"
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
{{- end }}
