apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: triggers.workflows.diamond.ac.uk
spec:
  group: workflows.diamond.ac.uk
  names:
    kind: Trigger
    plural: triggers
    singular: trigger
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              enabled:
                type: boolean
                default: true
              webhook: &generic_message
                type: object
                properties:
                  eventName: 
                    type: string
                  workflow:
                    type: object
                    required: [template]
                    properties:
                      template:
                        type: string
                      parameters:
                        type: array
                        default: []
                        items:
                          type: object
                          properties:
                            name: 
                              type: string
                            path:
                              type: string
                            default:
                              x-kubernetes-int-or-string: true
                          required: [name]
                required:
                  - workflow
                  - eventName
              stomp: *generic_message
            oneOf:
              - required: [webhook]
              - required: [stomp]
        required:
          - spec
    subresources:
     status: {}
