openbao:
  server:
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = 1
          }
          storage "raft" {
            path = "/openbao/data"
          }
          telemetry {
            unauthenticated_metrics_access = "true"
          }
          seal "static" {
            current_key_id = "123456789"
            current_key = "file:///openbao/secrets/unseal.key"
          }
      auditStorage:
        enabled: true
    volumes:
      - name: unseal-key
        secret:
          secretName: openbao-secret
    volumeMounts:
      - name: unseal-key
        mountPath: /openbao/secrets
        readOnly: true
    injector:
      enabled: true
