---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth
  namespace: workflows
spec:
  encryptedData:
    client-id: AgCSI7hH/bRVX+SAITTACq1czR+OqiJ0y/HsJwjMMkCqKqe+dzX82mFDOoH7k2Dr9oi/px2IetAu8yMAtHyoIZgD4cvOFqx4R39wO9sgYbVxZJ7nEWjpO1paWlCzJbhTklVkabQnuWNjEzO25lloxr5DwG/lSUIyILfvHzLaCMR2mY0c00AdUNzfTEZN9wb6Ovbbx8yjgbfD6N4ckvFXU6qPLxbaOIBiwsB2r9KuD8/RcFxZlCiuyVuPSGfJKwOzmalRJUBlwf941o4VyNSaeL0Ofm3vVOkPovHTZxgvt4NxQQLCeo6dyC8tyjqDSEfCozppFPZKUMyPPVJUOC68siMmMr3lK+VlZ3PmCC/Vz0HYMmGTU/dLZnij6D3KR+Tpcad2bk50Ps0nFVCS90/sxyUs4hgOAhNdQTcyxJbmYy5+C8HSindecJG+haOG8q+TVrpfLV5sT0/QCd2eM9gmBKKAnaqSdOPbXh4iMqcV0ZbNNRX1waUBPXxL7gJqrHzGvBTWTuLCTtORw+Ks7RdwoS9KEmCiT4fTZn6FXGQQnd4zHkbET2a/ed+QxKc2+UQYXR07YkYB0DntENu2xnd54Wg+KOqjo+ZkjnNKnSzWjFy9pE3MQeKKpQJwuTlKKPlSr9IWD8BVglBrp89Frd7MH9Z/Sb6RIuT2Fv7viinIJLjeOtZf12NPK5QarIfNzq4W8fjUFFJ0HJIdFXwuAejB9yvoDA==
    client-secret: AgAflMjrUSdzx2FtYnnmAemTi2jJnyF8BnAJ1segXBomgWHO3xwuOep9JL/EE0HB8HSzu/DCWjC0gTkJc8//bfDugpvJfZSysr4lxPOIli7BLGzAzG1xNi8EmmfgWG9fqa1QUxfKbkUsrJAE/gfdWvAYLqzOUFj7nRMRqomSLnphh3pmiYHtTFHWT8koy7PUVAj99aTOJT7MHHojlsZ74gmdLlPIJTsWLkdHqbZB3GkeBrE2qOHVWmLYiesJ00EAoxQ9dD9z7excr5Ow7ZBXz6Wq3BNManUlOEPEuXpWcy5shQNarvocoPHDFzobiRFp/KIRoHOcDDvBIpA6DTAlvD6De9PaWqMAMYg31OSfNW0gIu1i/zDnQmrVP8qipbtoTCGLom2xzrkpUh8NW6ZrlAp2J5Yykoz8q1ZQ5gQ1FYAMkHZG5Eis4TFrAQw6AONL3hSZPtYQYeSUzUxVrUtrr98e4vymalC3lXZQNcWU6HXe3dJHWm4BwFVhrkjUdNQAbQ94OYZm1Db/maFqFGeeXvPKpjtgnbleIAzgJf16XEBWVslARAdD44G5c22Vz4LXwgqORn39C9uof8qO5sRuB1il16rLJhpkGLW5TafaUOLBaKIh+/52WavxdmlYkKJwDiN1vWNAN5pbW6SY060JAdkNn8Qot0xhVky8ZKhgLpObL7ElvlGyh8JMi9AG4gRvAjghq3gEA85s98gG4ftUudzR9U54KY+CCGKWHM0GDyxBbA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth
      namespace: workflows
