{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: workflows
spec:
  encryptedData:
    client-id: AgB6cWGK5n9LSkX29hVE82ERqV8B3+PU5va4O4s4Dbmk6/IRiJ0P8dn+Xkc0D57dx71HkhkZ4I0mQKj/T4ZfSE0NK7yW4OXCobQMQC3532MQHlBU6gweaAcak89fKgACLM9xCe23JKr9IlSROaNTHEhrpFktoq89PRh8u4zVo0wFsUNpxqqc/LZo/ICC/2CGht3AMxKlcDV66f1XE9GEYMNEHV5qXxq4dCrzBXnTgJZ5aTLUpW0xHUfYvPSmZ2kynGS2UTSrArbp++nphO9hzKg6Id6hPuqeptXO907gDeR1rykEXZkFmVuROWXMdGna/4Cgd5whAktkt9LeURvwa5zQ3UA6y+P2bCHPtKMN4760k+1GTiC3fP+YJkRIjgGTF+TJVKdSzJ6fZ5794IVZ/apdlrapxED7+v8uGRdW+RymrHUMZ26tj0FiSiW0wjvVq4v4GgpxTqmnHF+0U/Rv5402FkASh5/0G52gOAKX7Y/Cur2qozbxy/RVstpiV7BZJb3+8+0PdyUr5znY1tHCJjHeF6T8f5p5BQaMARkIFCkpxW9Q3Lt5iyGLWDsRevuw+nGuQTBfXbcTA6ThMIK1g7qNMH60Roj+robO4SKdWXedB+qEdLMerVOlmagC/EeF9gGZ2NCjTfu3blNjkLdhCV25fJAxhyQC/OwBug585nHA8Kz9jowsFND4+xn0jMNm1nq586687rbc3F4J1fMNQ/FOkg==
    client-secret: AgB+r2lmnpgSCCnPVfLa24mC1u+nut4WXUVfVWgcDVZQKzVIniZWWa6HPxO+B/V1apcZ60XuyFZGCaEXoFRULRSD/BUOuWvmMnKjU5V15UwOuOZUS39yP0smHRZ2FRfJ/fMbARW6iBt+hfnGZzt2FlIVBiXnQNcgAK9cI0pz17jDeNThT/wvsjNfRkx+UiBzhoa9eukSWMD84+Yi/gllUgDMQcEo2Ej+Ndc3/unlPxSlsKkHGCFpBuJiRqrhfJpJ272hrMgj0ZMY6FgWvg68ZixON7FAO4djuRpo12YWFDWGmKO8UoGEWeQaHQDDioB3I2wizynLItGFF/VrmoTgKuWknET0jktB27wUGT/fsvni5qNKrNvWfBUvMfy9voicWWmDR2ZkH9StUUj8QqaWBpv13qZBZ0mk1HM1CheUehfb0U5rHj9kMUJnHwkrvoPSWuQO94TG+U3Sg6V+yFdnQk+jfCrt+TroD5FHYppx564RiEC+qlfRlVOaZz6L1QFeejbN7XK+uUC4UH0ldKHyzw4GZdpkiTOfShOdKi9Z4wlZNCRrb2t51ghtidXlN3Cfk6ZTXSkNfYxyJ5+c7YHJvMhvZkhcJ6yg2cLXARp3eBNJhATWVcbLNFCL+KuR2oTpH6DhjUhAUSrhZjSu/L8rK1DtgNRYHjfI1Nb8xjdny5RdSETtbutHbkevTY8UuQjY3BFaTCON7w+sGEz0v0PXfBiCD6OKHWQ1LRS+UkXVcWaFiA==
  template:
    metadata:
      name: grafana-oauth
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    client-id: AgAZtZSY6p7+DgcrpquiQrk7+MrbvPNGGBb6oy58dftYo7exdsY6V8AvZTEpuEAmspC9NLt330MDyDXLYFX99OlLLlukJUuyx8cA5mx1l9sC72qDCRok2Zi4Y7K9gHwEXyPI327EPV7aGwZjtT0Cauz4xP4sRs0zpoPcbu2aseqf6tWR6KtXOO2zylC3xZwTN74mQRSpsePXgPhKjl+rdVcn7f6S0lDXez4EfaTpAG2HNTjBk/8Oh1066kNgUhEHIidce4v2eLHr15bmShrggkqaZHxDVz9lVGXo5GQcqpxjN92XOfESdI9hoSpvQ2tqFqZemK84SllOOp9EiG0jXr+GUuJ7E5LR+81XR63N/AqyxmWv3gHKSwwsvsC4GBc7hIFKU25hZV0ZVvZyo+ip9s0s0EJsGvIoZO843rFinGbQ428Q8O/IqhdtNQ9zJFPWmMb5QbVuiY8LuHg4wRig9xN/s+TSY7I+lS6IeWnDzb2xiyVJtHLHZ0LMR9pRDUryv+glmrUoMGyeXdGcvlIJbuSkMxttXaj+gPeKm+cTBkrhg6ageR5MYO4ZwvPhhtFJp/fm+ffZ69kieQr50sDOJlv7LePu/kDQ0NHKN3D1VpyiCtZMzAjCMr7ZM9kYjg8/jcLnuVL/1FriOWPQ9+v8Gt3XRFO3/c5CusAH3ZtlRrwUXa77zxEjGBeaj3IyxtkHTMtIfGyNoY5FKwzFNt0u4yr0DqRFwjXjQCjF
    client-secret: AgCSXx055+wPexm82zq4ZcC+ChZLW2fgXTYKY0rKTnAWgpelT6P+KUG4rQOxIhMUptgj6r7pfqaa1FW0u1Y02C/l0pE+KDfIIgYeYYL1UCBNU+7tfpQd4LqyrI0ljHoB1IqtmBP+ItnwfViVmbUhCw/Lo55JWMDSpYuoZAaYHdvl6IIzoR04sZeFqpf58y2/cB695Mu5dRwanMli0NCfF04SuoBodpRN7EoxATHcBNVSUDSSmpLdqjAw5TgFXbIx5RdmQV6FnTCOkmS0xoToVCk1ipddDvFB7hbALbZPBh7pfGwB6jPTZK4vV+8SsPFDLlNjELsty8+GNuVcXISUIfmBVPkt6oueTgP8UBLlYEANV88gIB/VSLVIv0bXPzhfd4XTytEUH1D0aDBa7a5GK1hgzaA7V458JWeYdWl9r9IVRhUwciJnT62F0pdqTLkCOcs0ZK2kSwe2x8UJqsXxZ7dyEn++uDYB/Zz9Mf/XsI/26snNW6iY9zUnkI4MEIxMmC3VMnvoeXpxXcIIq3kUU7o/dlvZxv8kqIMgtGdNZzvABsGnXxiA6Gslvw2nAPJgbdcXDkvbzhkFryDeL+4Hz44u2r4Dad7K2pXD5HE4mu4DuVjF3HaB/apvfda8OF2MfLivKOTUV4ok5UYNzgWiLroM1JAtwjnYd9Y07Hadb+PKPahEysLg1lesRNLO0UWJ3jajaI3Eve7SllyXd8xVDfp5qtRmua6tODDC4cLfWEv76g==
  template:
    metadata:
      name: grafana-oauth
      namespace: {{ .Release.Namespace }}
{{- end }}
