{{- if eq .Values.cluster "argus" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: workflows
spec:
  encryptedData:
    client-id: AgB6cWGK5n9LSkX29hVE82ERqV8B3+PU5va4O4s4Dbmk6/IRiJ0P8dn+Xkc0D57dx71HkhkZ4I0mQKj/T4ZfSE0NK7yW4OXCobQMQC3532MQHlBU6gweaAcak89fKgACLM9xCe23JKr9IlSROaNTHEhrpFktoq89PRh8u4zVo0wFsUNpxqqc/LZo/ICC/2CGht3AMxKlcDV66f1XE9GEYMNEHV5qXxq4dCrzBXnTgJZ5aTLUpW0xHUfYvPSmZ2kynGS2UTSrArbp++nphO9hzKg6Id6hPuqeptXO907gDeR1rykEXZkFmVuROWXMdGna/4Cgd5whAktkt9LeURvwa5zQ3UA6y+P2bCHPtKMN4760k+1GTiC3fP+YJkRIjgGTF+TJVKdSzJ6fZ5794IVZ/apdlrapxED7+v8uGRdW+RymrHUMZ26tj0FiSiW0wjvVq4v4GgpxTqmnHF+0U/Rv5402FkASh5/0G52gOAKX7Y/Cur2qozbxy/RVstpiV7BZJb3+8+0PdyUr5znY1tHCJjHeF6T8f5p5BQaMARkIFCkpxW9Q3Lt5iyGLWDsRevuw+nGuQTBfXbcTA6ThMIK1g7qNMH60Roj+robO4SKdWXedB+qEdLMerVOlmagC/EeF9gGZ2NCjTfu3blNjkLdhCV25fJAxhyQC/OwBug585nHA8Kz9jowsFND4+xn0jMNm1nq586687rbc3F4J1fMNQ/FOkg==
    client-secret: AgB+r2lmnpgSCCnPVfLa24mC1u+nut4WXUVfVWgcDVZQKzVIniZWWa6HPxO+B/V1apcZ60XuyFZGCaEXoFRULRSD/BUOuWvmMnKjU5V15UwOuOZUS39yP0smHRZ2FRfJ/fMbARW6iBt+hfnGZzt2FlIVBiXnQNcgAK9cI0pz17jDeNThT/wvsjNfRkx+UiBzhoa9eukSWMD84+Yi/gllUgDMQcEo2Ej+Ndc3/unlPxSlsKkHGCFpBuJiRqrhfJpJ272hrMgj0ZMY6FgWvg68ZixON7FAO4djuRpo12YWFDWGmKO8UoGEWeQaHQDDioB3I2wizynLItGFF/VrmoTgKuWknET0jktB27wUGT/fsvni5qNKrNvWfBUvMfy9voicWWmDR2ZkH9StUUj8QqaWBpv13qZBZ0mk1HM1CheUehfb0U5rHj9kMUJnHwkrvoPSWuQO94TG+U3Sg6V+yFdnQk+jfCrt+TroD5FHYppx564RiEC+qlfRlVOaZz6L1QFeejbN7XK+uUC4UH0ldKHyzw4GZdpkiTOfShOdKi9Z4wlZNCRrb2t51ghtidXlN3Cfk6ZTXSkNfYxyJ5+c7YHJvMhvZkhcJ6yg2cLXARp3eBNJhATWVcbLNFCL+KuR2oTpH6DhjUhAUSrhZjSu/L8rK1DtgNRYHjfI1Nb8xjdny5RdSETtbutHbkevTY8UuQjY3BFaTCON7w+sGEz0v0PXfBiCD6OKHWQ1LRS+UkXVcWaFiA==
  template:
    metadata:
      name: grafana-oauth
      namespace: workflows
    type: Opaque
{{- else if eq .Values.cluster "pollux" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    client-id: AgA5Kv8S3fX2JYAR2Li7wPFmoE0nykOBKyjYtHhXaMD/0+ZwLkX/1Uw+XIwCtPGElYxYVonSdaH7Zq8E9+9f9qbviFdx/eGdMM/UNANcWMnvdSOw+vtmQNvgBw5vPXZt2f/J9YgVYvgMhFx/YFI/Sm3zNMrDKm6UAskr/XAfaMiySnYp0pQ9Y2S7kwPTYFKwg8NEDD2C2aC+kLhRmFlsVeKuHRl9N6Cozjurwe26jIX7j/9//4BeYZvNXDq+yzNwPAyv8LDypkMK4pVU1Tt5K6ltEJkwPMr1px+msS/+GMLTjBKyTJwjhArCarpXF0u8b3o3t1Ls5M/BhVlucfE7r2zKZPVb2B7MsPL7WKX5rp5tREauYPqGvUSGFCF31lKwR2MU/yBf6GLjzUtJCskHZYj38gQRXSGCFl3kYgvm2uCFOnl/yU1AqK1aDmL2SzRloShlPBBd/pLr04zNAy9z40yZNpIDiyMtJezJaRyUtqsTc3hQ3e6Qe4ONdFqEP3PWoOM1bRDvtwH5Biqb7iSVZgFYVlJd/WNrAJK/g4Tv3B8GMaA3HZFm3wYDvpedC/ROiOCmvndtbr8dRcjo7wYazlT/JhP5ze1QIND1KDlCPliErBaSoVYTHRLZI6R7B5tQ2m7K0e87aNRNiXhr7kGni0JRO6vYk4TW2UESSDEbGwIQNLp59JVvOc0JiQ4IOL5klj21JKSzfTZyW5Cc3TmdVhkEFOAj+kfyV/Cx
    client-secret: AgBvpwzacRpBQIlnM/MH9Ov0Hf/PlmX9Tn2jA668dbGTU2Aq60bPO7zj54IvMl04JVqpdp8CwoNMtv3AP4sRLIISmDgeBMqP5Qm1yicXUX2kzMsw5l95j5DFkG2JXEDrud5isqgR26Cj8Vr5bQ0zcycq3iVRRQBVosa7jI81rBUHqq5Ohj0T1eUjx0imp9C3Q7jdfN7zIlFnXTrQfPeBLmyeTRJminYuzLhaHY/7wL5JEYXxmg9WQgY40wPbYgQiG+1CoDweent3H5THMNQwrippi+WG9Pk7KorWjnnie81IsiGAWESYXMHKxDQAGiIobwEVIakYOTI8JvLc/8sGMqSyvatMN+9lJTNENFcpFqF5UQXNr+y8HhvK3hCChVqQzlZQZxGaY1rqzQ+BzcHxSfHFlXVP32f5+I0BsAL9KrrHkRNEwtKmKIA7H2NAXNQhtq3ahRpgDYRrrt6MTcJptQPW2/vGOGPBDCLvXnP88kGaMl09sI8/fjHYSGGdYj6Wd1l+m64sxLrya/KKfxpCQ1YVLGziHcKkjFwe3rg2Ve45V1SOzq6c0bdIyWs/uDp58tqSPhR96IXRqyBk3aHP+szx54AO9W4nuYFiA2LsUVL5YqEuPNrWVkCkNMwxzU6xfq3+n7fW/2L/6SyP88NhJWMeR4IxNE1NUH6puGMvgOvgGdda9vd2+ID+Qqv0azJY7f1Wq+8aWfxpY3DAxDGh2rGwcVByXA5cOjPAEE9/4cVkTg==
  template:
    metadata:
      name: grafana-oauth
      namespace: {{ .Release.Namespace }}
{{- end }}
