apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-scripts
data:
  rclone-upload.sh: |
    SNAP="${SNAPSHOT_DIR}${SNAPSHOT_NAME}${SNAPSHOT_EXT}"

    # Check for today's backup
    if [ ! -s "$SNAP" ]; then
      echo "Backup does not exist"
      exit 1
    fi

    # Want to track if any rclone command fails.
    failed="false"

    # Timestamp
    mv $SNAP "${SNAPSHOT_DIR}${SNAPSHOT_NAME}-$(date +%Y-%m-%d)${SNAPSHOT_EXT}" || failed="true"

    echo "backing up to echo S3"
    rclone copy ${SNAPSHOT_DIR} echo:dls-workflows-prod/${PREFIX}
    rclone_echo_s3_exit_code=$?

    if [ $rclone_echo_s3_exit_code -eq 0 ]; then
      echo "rclone copy to echo s3 succeeded"
    else
      echo "rclone copy to echo s3 failed"
      failed="true"
    fi

    # Delete old backed up objects, with age >= 2 days.
    echo "deleting old backups from echo s3"
    rclone delete --min-age=2d --include "*${SNAPSHOT_EXT}" echo:dls-workflows-prod/${PREFIX}
    rclone_delete_echo_s3_exit_code=$?

    if [ $rclone_delete_echo_s3_exit_code -eq 0 ]; then
      echo "rclone delete old objects in echo s3 succeeded"
    else
      echo "rclone delete old objects in echo s3 failed"
      failed="true"
    fi

    # If any rclone command failed, then return non-zero.
    if [ "$failed" = "true" ]; then
      exit 1
    fi

  rclone-download.sh: |
    echo "Starting script"
    LAST=$(rclone lsf -R --files-only --include "${SNAPSHOT_NAME}*${SNAPSHOT_EXT}" echo:dls-workflows-prod | sort | tail -1)
    if [ -z "$LAST" ]; then
      echo "No backups found in bucket"
      exit 1
    fi
    echo "Downloading $LAST"
    rclone copyto -P echo:dls-workflows-prod/${LAST} /snapshot/snapshot${SNAPSHOT_EXT}
    if [ "$RESET_ETCD" = true ]; then
      rm -rf /var/lib/etcd
      mkdir -p /var/lib/etcd
    fi
