apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cluster-templates
  labels:
    workflows.diamond.ac.uk/science-group-examples: "true"
    workflows.diamond.ac.uk/type: "live"
  annotations:
    workflows.argoproj.io/title: cluster-templates
    workflows.argoproj.io/description: |
      A simple ClusterWorkflowTemplate with a full pipeline (generate → lint → test → run).
      workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"
spec:
  entrypoint: pipeline
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
      - name: size
        value: "2000"
      - name: memory
        value: "20Gi"

  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: netapp

  templates:
    - name: pipeline
      dag:
        tasks:
          - name: generate-files
            template: generate-files

          - name: lint
            template: lint
            dependencies:
              - generate-files

          - name: test
            template: test
            dependencies:
              - lint

          - name: run
            template: run-job
            dependencies:
              - test
            arguments:
              parameters:
                - name: visitdir
                  value: "{{workflow.parameters.visitdir}}"

    - name: generate-files
      container:
        image: python:3.11-slim
        command: ["sh", "-c"]
        args:
          - |
            echo "Creating fake Python project..."
            mkdir -p /workspace/tests
