apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: simple-cluster-template

  labels:
    workflows.diamond.ac.uk/type: "live"
    workflows.diamond.ac.uk/science-group-examples: "true"

  annotations:
    workflows.argoproj.io/title: simple-cluster-template
    workflows.argoproj.io/description: |
      Minimal ClusterWorkflowTemplate for testing long-running pod.
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"

spec:
  entrypoint: hello

  # This ensures workflow itself is marked correctly
  workflowMetadata:
    labels:
      workflows.diamond.ac.uk/type: "live"

  #This is what actually controls scheduling (Kueue)
  podMetadata:
    labels:
      kueue.x-k8s.io/queue-name: live-queue
      kueue.x-k8s.io/priority-class: high
      workflows.diamond.ac.uk/type: "live"

  templates:
  - name: hello
    container:
      image: alpine:3.19
      command: ["sh", "-c"]
      args:
        - |
          echo "Pod starting..."
          for i in $(seq 1 180); do
            echo "Running... $i"
            sleep 1
          done
          echo "Done after ~3 minutes"
