apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: division
  labels:
    workflows.diamond.ac.uk/science-group-examples: "true"
  annotations:
    workflows.argoproj.io/title: Division test
    workflows.argoproj.io/description: |
      Takes a numerical input and returns the remainder, output float, and output string
      to a json file
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"
spec:
  entrypoint: division
  arguments:
    parameters:
      - name: numinput
        value: "200"
      - name: numdivisor
        value: "3"
  volumeClaimTemplates:
  - metadata:
      name: output-dir
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 1Mi
      storageClassName: netapp
  templates:
    - name: division
      inputs:
        parameters:
          - name: numinput
      script:
        image: python:3.12
        volumeMounts:
        - name: output-dir
          mountPath: /output-dir
        command: ["python"]
        source: |
          import json
          x = int("{{workflow.parameters.numinput}}")
          y = int("{{workflow.parameters.numdivisor}}")
          div=x/y
          intdiv=x//y
          remain=x%y
          dictionary_of_results={"divide":div,"integer divisor":intdiv,"remainder":remain}
          with open("/output-dir/output.json","w") as otpt:
            json.dump(dictionary_of_results,otpt)
      outputs:
        artifacts:
          - name: results
            path: /output-dir/output.json

