
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-cli-test
  labels:
    workflows.diamond.ac.uk/science-group-examples: "true"
  annotations:
    workflows.argoproj.io/title: Example
    workflows.argoproj.io/description: |
      This workflow is used to test the workflows CLI
      with a simple long-running Hello World example.
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"
spec:
  entrypoint: hello-sleep
  templates:
    - name: hello-sleep
      container:
        image: alpine:3.18
        command: [sh, -c]
        args:
          - |
            echo "Hello World from workflows CLI"
            echo "Sleeping for 20 seconds... Zz... ZZzzz.."
            sleep 20
            echo "Done"
