apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dawn-powder-calibration
  annotations:
    workflows.argoproj.io/title: DAWN Powder calibration
    workflows.argoproj.io/description: |
      Runs the DAWN command-line powder calibration from a given config.json file. This file, along with input image path,
      output path and initial calibration should all be at the root level within the supplied config path.
    
    workflows.diamond.ac.uk/parameter-schema.confdir : |
      {
        "type": "string",
        "minLength": 1,
        "default": "/dls/science/groups/das/ExampleData/powder/app_test"
      }
    workflows.diamond.ac.uk/parameter-schema.fixparam : |
      {
        "type": "string",
        "oneOf": [
          {
            "const": "",
            "title": "Nothing fixed"
          },
          {
            "const": "-fixedWavelength",
            "title": "Fixed wavelength"
          },
          {
            "const": "-fixedDistance",
            "title": "Fixed distance"
          }
        ],
        "default": ""
      }
    workflows.diamond.ac.uk/parameter-schema.fixvalue: |
      {
        "type": "number",
        "minimum": 0,
      }
    
    workflows.diamond.ac.uk/ui-schema: |
      {
        "type": "VerticalLayout",
        "elements": [
          {
            "type": "Control",
            "label": "Path to config directory",
            "scope": "#/properties/confdir"
          },
          {
            "type": "Control",
            "label": "Fix wavelength or distance?",
            "scope": "#/properties/fixparam"
          },
          {
            "type": "Control",
            "label": "Wavelength (Angstrom)",
            "scope": "#/properties/fixvalue",
            "rule": {
              "effect": "SHOW",
              "condition": {
                "scope": "#/properties/fixparam",
                "schema": { "const": "-fixedWavelength"}
              }
            }
          },
          {
            "type": "Control",
            "label": "Distance (mm)",
            "scope": "#/properties/fixvalue",
            "rule": {
              "effect": "SHOW",
              "condition": {
                "scope": "#/properties/fixparam",
                "schema": { "const": "-fixedDistance"}
              }
            }
          }
        ]
      }
spec:
  entrypoint: run-calibration
  arguments:
    parameters:
      - name: confdir
        value: ""
      - name: fixparam
        value: ""
      - name: fixvalue
        value: 0

  templates:
  - name: run-calibration
    script:
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Duser.name=dawn -Duser.home=/tmp/"
      image: ghcr.io/jamesdoingstuff/dawn:latest
      volumeMounts:
      - name: config-dir
        mountPath: "{{ workflow.parameters.confdir }}"
      - name: tmp-dir
        mountPath: /tmp
      workingDir: /tmp-dir
      command: [/bin/bash]
      source: |
        fixflag=""
        if [ {{ workflow.parameters.fixparam }} = "" ]; then
          fixflag="{{ workflow.parameters.fixparam }} {{ workflow.parameters.fixvalue}}"
        fi
        /dawn_workspace/dawn $fixflag -configuration /tmp -consoleLog -noSplash -data @none \
        -application uk.ac.diamond.scisoft.diffraction.powder.application.powdercalibrate  \
        -path {{ workflow.parameters.confdir }}/config.json

    podSpecPatch: |
      containers:
        - name: main
          resources:
            requests:
              memory: 4Gi
            limits:
              memory: 4Gi
    volumes:
    - name: config-dir
      hostPath:
        path: "{{ workflow.parameters.confdir }}"
        type: Directory
    - name: tmp-dir
      emptyDir: {}

    outputs:
      artifacts:
      - name: result
        path: "{{ workflow.parameters.confdir }}/result.nxs"
        archive:
          none: {}
      - name: dawn-logs
        path: /tmp/dawn-dawn.log
        archive:
          none: {}
