apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate

metadata:
  name: basic-runner

  annotations:
    workflows.diamond.ac.uk/owner: "science"
    workflows.argoproj.io/title: "basic-runner"
    workflows.argoproj.io/description: "Very basic workflow with one run step."

  labels:
    workflows.diamond.ac.uk/category: "science"
    workflows.diamond.ac.uk/type: "live"

spec:
  entrypoint: run

  templates:

    - name: run
      container:
        image: alpine:3.19

        command: ["sh", "-c"]

        args:
          - |
            set -e

            echo "Starting workflow..."

            for i in $(seq 1 20); do
              echo "[$i/20] Workflow running at $(date)"
              sleep 3
            done

            echo "Workflow complete"