apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: python-hellow
  annotations:
    workflows.diamond.ac.uk/type: live
    workflows.argoproj.io/description: |
      Just a basic test workflow.
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"
  labels:
    workflows.diamond.ac.uk/science-group-examples: "true"
    kueue.x-k8s.io/priority-class: high

spec:
  entrypoint: pipeline
    
  templates:

      - - name: run
          template: run-job
          arguments:
            parameters:
               - name: visitdir
                 valueFrom:
                    configMapKeyRef:
                      name: sessionspaces
                      key: data_directory
            # parameters:
            #   - name: visitdir
            #     value: "{{ workflow.parameters.visitdir }}"



  #LINT

  - name: lint
  #RUN STEP
  - name: run-job
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
    container:
      image: alpine:3.19
      command: [sh, -c]
      args:
        - |
          echo "Pipeline completed
          echo "VisitDir = {{ inputs.parameters.visitdir }}"
          echo "Done"


