apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: workflow-of-workflows
  labels:
    workflows.diamond.ac.uk/science-group-examples: "true"
  annotations:
    workflows.argoproj.io/title: Workflow Of Workflows
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/workflows"
    workflows.diamond.ac.uk/authenticated: "true"
spec:
  entrypoint: entry
  templates:
    - name: entry
      steps:
        - - name: run-workflow
            template: curl
            arguments:
              parameters:
                - name: cmd
                  value: |
                    curl -v --request POST ${GRAPH_PROXY_URL} -H "Content-Type: application/json" -d '{"query": "mutation{ submitWorkflowTemplate(name: \"conditional-steps\", visit: {proposalCode: \"ks\", proposalNumber: 10000, number: 1}, parameters: {}){     name   } }" }'

    - name: curl
      inputs:
        parameters:
          - name: cmd
      container:
        image: curlimages/curl:8.15.0
        command: ["/bin/sh", "-c"]
        args: ["{{inputs.parameters.cmd}}"]
