name: Test internal runner

on:
  push:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ["iris-cpu"]
    container:
      image: nvidia/cuda:11.6.2-devel-ubi8
      options: --user 1000:1000
    steps:
      - uses: actions/checkout@v4
