name: Test internal runner

on:
  push:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ["iris-cpu"]
    container:
      image: summerwind/actions-runner:latest
      options: --user 1000:1000
    steps:
      - uses: actions/checkout@v4
